name: UmiLog
options:
  bundleIdPrefix: app.umilog
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  developmentLanguage: en
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    DEVELOPMENT_TEAM: "" # Set your team ID here
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    WATCHOS_DEPLOYMENT_TARGET: "10.0"
    ENABLE_PREVIEWS: YES
    SWIFT_STRICT_CONCURRENCY: complete

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    version: 6.24.0
  SQLCipher:
    url: https://github.com/Zetetic/SQLCipher
    version: 4.5.5

targets:
  UmiLog:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - UmiLog/
    dependencies:
      - package: GRDB
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: FeatureHome
      - target: FeatureLiveLog
      - target: FeatureHistory
      - target: FeatureSites
      - target: FeatureSettings
    settings:
      base:
        INFOPLIST_FILE: UmiLog/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: UmiLog/UmiLog.entitlements
        ENABLE_PREVIEWS: YES
    info:
      path: UmiLog/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - arm64
        CFBundleDisplayName: UmiLog
        CFBundleName: UmiLog
        CFBundleShortVersionString: "0.1.0"
        CFBundleVersion: "1"
        NSLocationWhenInUseUsageDescription: "UmiLog uses your location to suggest nearby dive sites and automatically fill site information."
        NSLocationAlwaysUsageDescription: "UmiLog uses your location to track dives and provide site recommendations."
        NSSpeechRecognitionUsageDescription: "UmiLog uses voice recognition for hands-free dive logging. All processing happens on your device."
        NSMicrophoneUsageDescription: "UmiLog uses the microphone for voice input during dive logging."
        NSPhotoLibraryUsageDescription: "UmiLog accesses your photos to attach images to dive logs."
        NSFaceIDUsageDescription: "UmiLog uses Face ID to secure your dive logs."

  UmiLogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - UmiLogTests/
    dependencies:
      - target: UmiLog
      - target: UmiDB
      - target: UmiCoreKit

  UmiLogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - UmiLogUITests/
    dependencies:
      - target: UmiLog

  # Core Modules
  UmiCoreKit:
    type: framework
    platform: iOS
    sources:
      - Modules/UmiCoreKit/Sources/
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.corekit

  UmiDesignSystem:
    type: framework
    platform: iOS
    sources:
      - Modules/UmiDesignSystem/Sources/
    dependencies:
      - target: UmiCoreKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.designsystem

  UmiDB:
    type: framework
    platform: iOS
    sources:
      - Modules/UmiDB/Sources/
    dependencies:
      - package: GRDB
      - package: SQLCipher
      - target: UmiCoreKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.db

  # Feature Modules
  FeatureHome:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureHome/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.home

  FeatureLiveLog:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureLiveLog/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.livelog

  FeatureHistory:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureHistory/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.history

  FeatureSites:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureSites/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.sites

  FeatureSettings:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureSettings/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.settings

schemes:
  UmiLog:
    build:
      targets:
        UmiLog: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - UmiLogTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release