name: UmiLog
options:
  bundleIdPrefix: app.umilog
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  developmentLanguage: en
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    DEVELOPMENT_TEAM: "" # Set your team ID here
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    WATCHOS_DEPLOYMENT_TARGET: "10.0"
    ENABLE_PREVIEWS: YES
    SWIFT_STRICT_CONCURRENCY: complete

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    version: 6.29.2
  MapLibre:
    url: https://github.com/maplibre/maplibre-gl-native-distribution
    branch: main

targets:
  UmiLog:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: UmiLog/
      - path: Resources/SeedData/sites_seed.json
        buildPhase: resources
      - path: Resources/Maps/dive_light.json
        buildPhase: resources
      - path: Resources/Maps/sites.geojson
        buildPhase: resources
      - path: Resources/Maps/shops.geojson
        buildPhase: resources
      - path: Resources/SeedData/sites_extended.json
        buildPhase: resources
      - path: Resources/SeedData/species_catalog.json
        buildPhase: resources
      - path: Resources/SeedData/dive_logs_mock.json
        buildPhase: resources
      - path: Resources/SeedData/sightings_mock.json
        buildPhase: resources
      - path: Resources/SeedData/sites_extended2.json
        buildPhase: resources
      - path: Resources/SeedData/sites_wikidata.json
        buildPhase: resources
    dependencies:
      - package: GRDB
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: FeatureMap
      - target: FeatureHome
      - target: FeatureLiveLog
      - target: FeatureHistory
      - target: FeatureSites
      - target: FeatureSettings
      - target: UmiLocationKit
      - target: DiveMap
    settings:
      base:
        INFOPLIST_FILE: UmiLog/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: UmiLog/UmiLog.entitlements
        ENABLE_PREVIEWS: YES
    info:
      path: UmiLog/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - arm64
        CFBundleDisplayName: UmiLog
        CFBundleName: UmiLog
        CFBundleShortVersionString: "0.1.0"
        CFBundleVersion: "1"
        NSLocationWhenInUseUsageDescription: "UmiLog uses your location to suggest nearby dive sites and automatically fill site information."
        NSLocationAlwaysUsageDescription: "UmiLog uses your location to track dives and provide site recommendations."
        NSSpeechRecognitionUsageDescription: "UmiLog uses voice recognition for hands-free dive logging. All processing happens on your device."
        NSMicrophoneUsageDescription: "UmiLog uses the microphone for voice input during dive logging."
        NSPhotoLibraryUsageDescription: "UmiLog accesses your photos to attach images to dive logs."
        NSFaceIDUsageDescription: "UmiLog uses Face ID to secure your dive logs."

  UmiLogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - UmiLogTests/
    dependencies:
      - target: UmiLog
      - target: UmiDB
      - target: UmiCoreKit

  UmiLogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - UmiLogUITests/
    dependencies:
      - target: UmiLog

  # Core Modules
  UmiCoreKit:
    type: framework
    platform: iOS
    sources:
      - Modules/UmiCoreKit/Sources/
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.corekit
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  UmiDesignSystem:
    type: framework
    platform: iOS
    sources:
      - Modules/UmiDesignSystem/Sources/
    dependencies:
      - target: UmiCoreKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.designsystem
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  UmiDB:
    type: framework
    platform: iOS
    sources:
      - Modules/UmiDB/Sources/
    dependencies:
      - package: GRDB
      - target: UmiCoreKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.db
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  # Feature Modules
  FeatureHome:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureHome/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.home
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  FeatureLiveLog:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureLiveLog/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
      - target: UmiLocationKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.livelog
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  FeatureHistory:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureHistory/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.history
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  FeatureSites:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureSites/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.sites
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  FeatureSettings:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureSettings/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.settings
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  FeatureMap:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureMap/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
      - target: UmiLocationKit
      - target: FeatureLiveLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.map
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  DiveMap:
    type: framework
    platform: iOS
    sources:
      - Modules/DiveMap/Sources/
    dependencies:
      - package: MapLibre
      - target: UmiCoreKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.divemap
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  UmiLocationKit:
    type: framework
    platform: iOS
    sources:
      - Modules/UmiLocationKit/Sources/
    dependencies:
      - target: UmiCoreKit
      - target: UmiDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.locationkit
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO
        INFOPLIST_KEY_NSLocationAlwaysAndWhenInUseUsageDescription: "UmiLog uses your location to automatically detect when you're at a dive site and suggest logging your dive."
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "UmiLog uses your location to suggest nearby dive sites."

schemes:
  UmiLog:
    build:
      targets:
        UmiLog: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - UmiLogTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release