name: UmiLog
options:
  bundleIdPrefix: app.umilog
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  developmentLanguage: en
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    # IMPORTANT: Set your Apple Developer Team ID before building
    # Find it at: https://developer.apple.com/account -> Membership -> Team ID
    DEVELOPMENT_TEAM: "ZK79P5HJFM"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    WATCHOS_DEPLOYMENT_TARGET: "10.0"
    ENABLE_PREVIEWS: YES
    SWIFT_STRICT_CONCURRENCY: complete
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      DEBUG_INFORMATION_FORMAT: "dwarf"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
      SWIFT_COMPILATION_MODE: "wholemodule"
      VALIDATE_PRODUCT: YES
      LLVM_LTO: YES

packages:
  # GRDB for SQLite database access
  # NOTE: SQLCipher encryption deferred - XCFramework forks have CSQLite module
  # issues with Xcode's explicit module builds. iOS File Protection (.complete)
  # is already enabled. Consider CocoaPods for SQLCipher in future.
  GRDB:
    url: https://github.com/groue/GRDB.swift
    version: 6.29.2
  MapLibre:
    url: https://github.com/maplibre/maplibre-gl-native-distribution
    version: 6.9.0
  Sentry:
    url: https://github.com/getsentry/sentry-cocoa
    version: 8.40.1

targets:
  UmiLog:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: UmiLog/
      - path: UmiLog/Assets.xcassets
        buildPhase: resources
      - path: Resources/SeedData/sites_seed.json
        buildPhase: resources
      - path: Resources/Maps/dive_light.json
        buildPhase: resources
      - path: Resources/Maps/dive_offline.json
        buildPhase: resources
      - path: Resources/Maps/umilog_min.json
        buildPhase: resources
      - path: Resources/Maps/umilog_underwater.json
        buildPhase: resources
      - path: Resources/Maps/sites.geojson
        buildPhase: resources
      - path: Resources/Maps/shops.geojson
        buildPhase: resources
      - path: Resources/SeedData/sites_extended.json
        buildPhase: resources
      - path: Resources/SeedData/species_catalog.json
        buildPhase: resources
      - path: Resources/SeedData/dive_logs_mock.json
        buildPhase: resources
      - path: Resources/SeedData/sightings_mock.json
        buildPhase: resources
      - path: Resources/SeedData/sites_extended2.json
        buildPhase: resources
      # REMOVED: sites_wikidata.json (10MB) - redundant, optimized tiles used instead
      - path: Resources/SeedData/optimized/tiles/manifest.json
        buildPhase: resources
      - path: Resources/SeedData/optimized/tiles/australia-pacific-islands.json
        buildPhase: resources
      - path: Resources/SeedData/optimized/tiles/caribbean-atlantic.json
        buildPhase: resources
      - path: Resources/SeedData/optimized/tiles/mediterranean.json
        buildPhase: resources
      - path: Resources/SeedData/optimized/tiles/north-atlantic-arctic.json
        buildPhase: resources
      - path: Resources/SeedData/optimized/tiles/red-sea-indian-ocean.json
        buildPhase: resources
      - path: Resources/SeedData/site_media.json
        buildPhase: resources
        optional: true
      - path: Resources/SiteImages/
        buildPhase: resources
        excludes:
          - "*.md"
    dependencies:
      - target: UmiDesignSystem
        embed: true
      - target: UmiCoreKit
        embed: true
      - target: FeatureMap
        embed: true
      - target: FeatureHome
        embed: true
      - target: FeatureLiveLog
        embed: true
      - target: FeatureHistory
        embed: true
      - target: FeatureSites
        embed: true
      - target: FeatureSettings
        embed: true
      - target: UmiLocationKit
        embed: true
      - target: UmiWatchKit
        embed: true
      - target: DiveMap
        embed: true
      - target: UmiDB
        embed: true
      - target: UmiAnalytics
        embed: true
      - package: MapLibre
      - package: GRDB
      - package: Sentry
    settings:
      base:
        INFOPLIST_FILE: UmiLog/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: UmiLog/UmiLog.entitlements
        ENABLE_PREVIEWS: YES
    info:
      path: UmiLog/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: LaunchBackground
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - arm64
        CFBundleDisplayName: UmiLog
        CFBundleName: UmiLog
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        NSLocationWhenInUseUsageDescription: "UmiLog uses your location to detect nearby dive sites, show your position on the map, and notify you when you arrive at a dive site for easy logging."
        NSSpeechRecognitionUsageDescription: "UmiLog uses voice recognition for hands-free dive logging. All processing happens on your device."
        NSMicrophoneUsageDescription: "UmiLog uses the microphone for voice input during dive logging."
        NSPhotoLibraryUsageDescription: "UmiLog accesses your photos to attach images to dive logs."
        NSFaceIDUsageDescription: "UmiLog uses Face ID to secure your dive logs."

  UmiLogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - UmiLogTests/
      - UmiLogTests/Fixtures/
      - UmiLogTests/Database/
      - UmiLogTests/ViewModels/
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: UmiLog
      - target: UmiDB
      - target: UmiCoreKit
      - target: FeatureMap
      - target: FeatureLiveLog
      - package: GRDB

  UmiLogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - UmiLogUITests/
    dependencies:
      - target: UmiLog

  # Core Modules
  UmiCoreKit:
    type: framework
    platform: iOS
    sources:
      - Modules/UmiCoreKit/Sources/
    dependencies:
      - sdk: Security.framework
      - sdk: LocalAuthentication.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.corekit
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  UmiDesignSystem:
    type: framework
    platform: iOS
    sources:
      - Modules/UmiDesignSystem/Sources/
    dependencies:
      - target: UmiCoreKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.designsystem
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  UmiDB:
    type: framework
    platform: iOS
    sources:
      - Modules/UmiDB/Sources/
    dependencies:
      - package: GRDB
      - target: UmiCoreKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.db
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  # Feature Modules
  FeatureHome:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureHome/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
      - package: GRDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.home
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  FeatureLiveLog:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureLiveLog/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
      - target: UmiLocationKit
      - package: GRDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.livelog
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  FeatureHistory:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureHistory/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
      - package: GRDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.history
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  FeatureSites:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureSites/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
      - package: GRDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.sites
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  FeatureSettings:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureSettings/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
      - package: GRDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.settings
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  FeatureMap:
    type: framework
    platform: iOS
    sources:
      - Modules/FeatureMap/Sources/
    dependencies:
      - target: UmiDesignSystem
      - target: UmiCoreKit
      - target: UmiDB
      - target: UmiLocationKit
      - target: UmiWatchKit
      - target: FeatureLiveLog
      - target: DiveMap
      - package: GRDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.map
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  DiveMap:
    type: framework
    platform: iOS
    sources:
      - Modules/DiveMap/Sources/
    dependencies:
      - package: MapLibre
      - target: UmiCoreKit
      - target: UmiDesignSystem
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.feature.divemap
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  UmiLocationKit:
    type: framework
    platform: iOS
    sources:
      - Modules/UmiLocationKit/Sources/
    dependencies:
      - target: UmiCoreKit
      - target: UmiDB
      - package: GRDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.locationkit
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "UmiLog uses your location to detect nearby dive sites and notify you when you arrive."

  UmiWatchKit:
    type: framework
    platform: iOS
    sources:
      - Modules/UmiWatchKit/Sources/
    dependencies:
      - target: UmiCoreKit
      - target: UmiDB
      - package: GRDB
      - sdk: WatchConnectivity.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.watchkit
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

  UmiAnalytics:
    type: framework
    platform: iOS
    sources:
      - Modules/UmiAnalytics/Sources/
    dependencies:
      - package: Sentry
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.umilog.analytics
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO

schemes:
  UmiLog:
    build:
      targets:
        UmiLog: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - UmiLogTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
