#!/usr/bin/env python3
"""
Part C — supplemental regions added to existing groups.
Each entry: {"group_id": str, "regions": [...]} — merged by build script.
"""

# Regions keyed by group_id — appended to matching groups in A+B
SUPPLEMENTAL_REGIONS: dict[str, list[dict]] = {

    "coral-triangle": [
        {
            "id": "derawan-sangalaki",
            "name": "Derawan & Sangalaki, Borneo",
            "country_id": "ID", "country": "Indonesia",
            "latitude": 2.28, "longitude": 118.22,
            "bounds": {"min_lat": 1.8, "max_lat": 2.8, "min_lon": 117.7, "max_lon": 119.0},
            "tagline": "Manta rays and jellyfish lakes",
            "best_season": "April–November",
            "defaults": {
                "averageDepth": 16.0, "maxDepth": 30.0, "averageTemp": 28.0,
                "averageVisibility": 15.0, "difficulty": "Intermediate",
                "curation_score": 9.0, "popularity_score": 8.0, "access_level": "boat",
            },
            "_sites": [
                ("Jellyfish Lake Kakaban", "Reef", "Beginner", ["jellyfish lake", "snorkel", "unique"], ["beginner-friendly"]),
                ("Sangalaki Manta", "Reef", "Intermediate", ["manta rays", "cleaning station"], ["big-animals"]),
                ("Derawan Housereef", "Shore", "Beginner", ["turtles", "macro", "shore"], ["beginner-friendly"]),
                ("Big Fish Country", "Reef", "Advanced", ["bumphead parrotfish", "schooling fish", "current"], ["big-animals", "advanced-challenges"]),
                ("Maratua Atoll", "Reef", "Intermediate", ["pristine atoll", "reef fish", "remote"], ["liveaboard"]),
                ("Turtle Nursery", "Shore", "Beginner", ["sea turtles", "nesting area"], ["big-animals", "beginner-friendly"]),
                ("Blue Trigger Wall", "Wall", "Intermediate", ["wall", "triggerfish", "current"], []),
                ("Barracuda Point Derawan", "Reef", "Advanced", ["barracuda tornado", "current", "schooling fish"], ["advanced-challenges"]),
                ("Stingray City Derawan", "Shore", "Beginner", ["stingrays", "shallow", "snorkel"], ["big-animals", "beginner-friendly"]),
                ("Sandy Ridge", "Shore", "Beginner", ["sandy", "garden eels", "macro"], ["macro-muck", "beginner-friendly"]),
            ],
        },
        {
            "id": "wakatobi",
            "name": "Wakatobi, Southeast Sulawesi",
            "country_id": "ID", "country": "Indonesia",
            "latitude": -5.3, "longitude": 123.7,
            "bounds": {"min_lat": -6.0, "max_lat": -4.5, "min_lon": 123.0, "max_lon": 124.5},
            "tagline": "Pristine reefs and high-end eco-diving",
            "best_season": "April–October",
            "defaults": {
                "averageDepth": 15.0, "maxDepth": 30.0, "averageTemp": 28.0,
                "averageVisibility": 22.0, "difficulty": "Intermediate",
                "curation_score": 9.2, "popularity_score": 8.2, "access_level": "boat",
            },
            "_sites": [
                ("Roma", "Reef", "Intermediate", ["pristine coral", "reef fish diversity"], []),
                ("Fan 38", "Wall", "Intermediate", ["sea fans", "wall", "current"], []),
                ("Blade", "Reef", "Advanced", ["current", "schooling fish", "pelagic"], ["advanced-challenges"]),
                ("Teluk Maya", "Reef", "Beginner", ["coral garden", "reef fish", "calm"], ["beginner-friendly"]),
                ("Coral Garden Wakatobi", "Reef", "Beginner", ["hard coral", "fish diversity"], ["beginner-friendly"]),
                ("Zoo", "Reef", "Intermediate", ["reef fish", "biodiversity"], []),
                ("Tekken", "Wall", "Intermediate", ["wall", "soft coral", "fish"], []),
                ("Cornucopia", "Reef", "Intermediate", ["hard coral", "diverse fish"], []),
                ("House Reef Wakatobi", "Shore", "Beginner", ["resort housereef", "macro", "fish"], ["beginner-friendly"]),
                ("Mola-mola Wakatobi", "Reef", "Advanced", ["mola mola", "deep", "current"], ["big-animals", "advanced-challenges"]),
                ("Teluk Waitii", "Reef", "Beginner", ["mangrove", "macro", "juvenile fish"], ["macro-muck", "beginner-friendly"]),
            ],
        },
        {
            "id": "flores-sea-indonesia",
            "name": "Flores Sea & Maumere",
            "country_id": "ID", "country": "Indonesia",
            "latitude": -8.6, "longitude": 122.2,
            "bounds": {"min_lat": -9.0, "max_lat": -8.0, "min_lon": 121.5, "max_lon": 123.0},
            "tagline": "Quiet reefs and WWII wrecks off the tourist trail",
            "best_season": "May–October",
            "defaults": {
                "averageDepth": 16.0, "maxDepth": 30.0, "averageTemp": 27.0,
                "averageVisibility": 15.0, "difficulty": "Intermediate",
                "curation_score": 8.5, "popularity_score": 7.0, "access_level": "boat",
            },
            "_sites": [
                ("Babi Island", "Reef", "Intermediate", ["coral", "fish diversity", "turtles"], []),
                ("Wuring Maumere", "Shore", "Beginner", ["shore", "macro", "reef fish"], ["beginner-friendly"]),
                ("Gili Banta", "Reef", "Advanced", ["current", "sharks", "pelagic"], ["big-animals", "advanced-challenges"]),
                ("Riung 17 Islands", "Reef", "Intermediate", ["protected", "reef fish", "turtles"], []),
                ("Labuan Bajo", "Reef", "Beginner", ["coral garden", "mangrove", "fish"], ["beginner-friendly"]),
                ("Ende Reefs", "Reef", "Intermediate", ["reef", "fish diversity"], []),
                ("Gunung Api", "Reef", "Advanced", ["volcanic", "unique formations", "current"], ["advanced-challenges"]),
                ("Solor Strait", "Drift", "Advanced", ["current", "pelagic", "sharks"], ["big-animals", "advanced-challenges"]),
            ],
        },
    ],

    "philippines": [
        {
            "id": "tubbataha-cagayancillo",
            "name": "Tubbataha Extensions & Cagayancillo",
            "country_id": "PH", "country": "Philippines",
            "latitude": 8.9, "longitude": 119.9,
            "bounds": {"min_lat": 8.5, "max_lat": 9.5, "min_lon": 119.5, "max_lon": 120.5},
            "tagline": "Remote UNESCO reefs beyond Tubbataha",
            "best_season": "March–June",
            "defaults": {
                "averageDepth": 20.0, "maxDepth": 40.0, "averageTemp": 28.0,
                "averageVisibility": 28.0, "difficulty": "Advanced",
                "curation_score": 9.3, "popularity_score": 7.5, "access_level": "liveaboard",
            },
            "_sites": [
                ("Cagayancillo Seamount", "Reef", "Advanced", ["hammerheads", "whale sharks", "remote"], ["big-animals", "liveaboard", "advanced-challenges"]),
                ("Basterra Reef", "Reef", "Advanced", ["pristine", "remote", "sharks"], ["big-animals", "liveaboard"]),
                ("Jessie Beazley Reef", "Reef", "Advanced", ["whale sharks", "remote", "pristine"], ["big-animals", "liveaboard"]),
                ("Apo Reef", "Reef", "Advanced", ["hammerheads", "thresher sharks", "large reef"], ["big-animals", "advanced-challenges"]),
                ("Apo Reef North Wall", "Wall", "Advanced", ["sheer wall", "pelagic", "sharks"], ["big-animals", "advanced-challenges"]),
                ("Apo Reef Lagoon", "Reef", "Intermediate", ["lagoon", "reef fish", "turtles"], []),
                ("Cagayan Ridge", "Reef", "Advanced", ["remote", "pristine", "pelagic"], ["big-animals", "liveaboard"]),
            ],
        },
        {
            "id": "leyte-ormoc",
            "name": "Leyte & Eastern Visayas",
            "country_id": "PH", "country": "Philippines",
            "latitude": 11.0, "longitude": 124.5,
            "bounds": {"min_lat": 10.0, "max_lat": 12.0, "min_lon": 124.0, "max_lon": 125.5},
            "tagline": "Thresher sharks and Surigao Strait",
            "best_season": "November–May",
            "defaults": {
                "averageDepth": 18.0, "maxDepth": 35.0, "averageTemp": 27.0,
                "averageVisibility": 18.0, "difficulty": "Intermediate",
                "curation_score": 8.8, "popularity_score": 7.8, "access_level": "boat",
            },
            "_sites": [
                ("Sogod Bay Threshers", "Reef", "Intermediate", ["thresher sharks", "deep water", "unique"], ["big-animals"]),
                ("Peter's Mound", "Reef", "Intermediate", ["coral mound", "fish diversity"], []),
                ("Canigao Channel", "Drift", "Advanced", ["current", "schooling fish", "sharks"], ["big-animals", "advanced-challenges"]),
                ("Surigao Strait", "Drift", "Advanced", ["extreme current", "pelagic", "sharks"], ["big-animals", "advanced-challenges"]),
                ("Padre Burgos Wall", "Wall", "Intermediate", ["wall", "soft coral", "fish"], []),
                ("Homonhon Island", "Reef", "Intermediate", ["remote", "reef fish", "pristine"], []),
                ("Dimasalang Seamount", "Reef", "Advanced", ["thresher sharks", "hammerheads", "deep"], ["big-animals", "advanced-challenges"]),
                ("Basdaku Beach", "Shore", "Beginner", ["shore", "reef fish", "coral"], ["beginner-friendly"]),
                ("Liloan Channel", "Drift", "Advanced", ["current", "macro", "unique critters"], ["macro-muck", "advanced-challenges"]),
            ],
        },
    ],

    "malaysia-borneo": [
        {
            "id": "sabah-northern-borneo",
            "name": "Sabah Northern Coast & Lankayan",
            "country_id": "MY", "country": "Malaysia",
            "latitude": 6.6, "longitude": 117.8,
            "bounds": {"min_lat": 6.0, "max_lat": 7.5, "min_lon": 116.5, "max_lon": 119.0},
            "tagline": "Whale sharks, wrecks, and remote atolls",
            "best_season": "April–October",
            "defaults": {
                "averageDepth": 16.0, "maxDepth": 30.0, "averageTemp": 28.0,
                "averageVisibility": 12.0, "difficulty": "Intermediate",
                "curation_score": 8.8, "popularity_score": 7.5, "access_level": "boat",
            },
            "_sites": [
                ("Lankayan Island", "Reef", "Intermediate", ["whale sharks", "reef fish", "macro"], ["big-animals"]),
                ("Jambatan Reef", "Reef", "Intermediate", ["reef", "fish diversity"], []),
                ("Pulau Selingan", "Shore", "Beginner", ["turtle island", "nesting turtles", "shore"], ["big-animals", "beginner-friendly"]),
                ("Pulau Mantanani", "Reef", "Beginner", ["dugong", "reef", "coral garden"], ["big-animals", "beginner-friendly"]),
                ("Layang Layang Atoll", "Reef", "Advanced", ["hammerheads", "thresher sharks", "remote", "walls"], ["big-animals", "liveaboard", "advanced-challenges"]),
                ("Kudat Reefs", "Reef", "Intermediate", ["remote", "reef fish", "pristine"], []),
                ("Bangi Wreck", "Wreck", "Intermediate", ["wreck", "reef fish", "coral growth"], ["wreck-capitals"]),
                ("Tunku Abdul Rahman Park", "Reef", "Beginner", ["protected", "reef fish", "snorkel"], ["beginner-friendly"]),
                ("Sulug Island", "Reef", "Beginner", ["coral", "reef fish", "turtles"], ["beginner-friendly"]),
                ("Sapi Island", "Shore", "Beginner", ["shore", "reef fish", "coral garden"], ["beginner-friendly"]),
                ("Mamutik Island", "Shore", "Beginner", ["protected reef", "shore", "macro"], ["beginner-friendly"]),
                ("Gaya Island", "Shore", "Beginner", ["mangrove", "macro", "seahorse"], ["macro-muck", "beginner-friendly"]),
            ],
        },
        {
            "id": "sarawak-borneo",
            "name": "Sarawak & Southern Borneo",
            "country_id": "MY", "country": "Malaysia",
            "latitude": 2.5, "longitude": 111.5,
            "bounds": {"min_lat": 1.5, "max_lat": 4.0, "min_lon": 109.0, "max_lon": 114.0},
            "tagline": "Undiscovered Borneo reefs",
            "best_season": "May–September",
            "defaults": {
                "averageDepth": 14.0, "maxDepth": 25.0, "averageTemp": 28.0,
                "averageVisibility": 10.0, "difficulty": "Beginner",
                "curation_score": 7.8, "popularity_score": 6.0, "access_level": "boat",
            },
            "_sites": [
                ("Talang-Talang Islands", "Reef", "Beginner", ["turtles", "nesting beaches", "reef"], ["big-animals", "beginner-friendly"]),
                ("Satang Island", "Reef", "Beginner", ["turtles", "coral", "fish"], ["beginner-friendly"]),
                ("Bako National Park", "Shore", "Beginner", ["shore", "macro", "unique critters"], ["beginner-friendly"]),
                ("Luconia Shoals", "Reef", "Advanced", ["remote", "pristine", "pelagic"], ["liveaboard", "advanced-challenges"]),
                ("Pulau Looe", "Reef", "Intermediate", ["reef", "fish diversity"], []),
                ("Tanjung Sirik", "Shore", "Beginner", ["shore", "reef fish", "coral"], ["beginner-friendly"]),
            ],
        },
    ],

    "southeast-asia-mainland": [
        {
            "id": "andaman-nicobar",
            "name": "Andaman & Nicobar Islands, India",
            "country_id": "IN", "country": "India",
            "latitude": 11.7, "longitude": 92.7,
            "bounds": {"min_lat": 6.0, "max_lat": 14.0, "min_lon": 92.0, "max_lon": 94.0},
            "tagline": "Pristine Indian Ocean reefs close to Thailand",
            "best_season": "November–April",
            "defaults": {
                "averageDepth": 16.0, "maxDepth": 30.0, "averageTemp": 28.0,
                "averageVisibility": 18.0, "difficulty": "Intermediate",
                "curation_score": 9.0, "popularity_score": 8.0, "access_level": "boat",
            },
            "_sites": [
                ("Barren Island Volcano", "Reef", "Advanced", ["volcanic island", "remote", "pelagic", "mantas"], ["big-animals", "liveaboard", "advanced-challenges"]),
                ("Cinque Island", "Reef", "Intermediate", ["pristine reef", "coral", "reef fish"], []),
                ("North Bay", "Reef", "Beginner", ["coral garden", "reef fish", "snorkel"], ["beginner-friendly"]),
                ("Elephant Beach", "Shore", "Beginner", ["shore", "reef fish", "coral"], ["beginner-friendly"]),
                ("Johnny's Gorge", "Wall", "Advanced", ["wall", "current", "sharks"], ["big-animals", "advanced-challenges"]),
                ("The Wall Andaman", "Wall", "Advanced", ["sheer wall", "pelagic", "schooling fish"], ["advanced-challenges"]),
                ("Rutland Island", "Reef", "Intermediate", ["remote", "pristine", "reef fish"], []),
                ("South Button", "Reef", "Advanced", ["sharks", "pelagic", "remote"], ["big-animals", "advanced-challenges"]),
                ("Mahatma Gandhi Marine Park", "Reef", "Beginner", ["protected", "coral", "fish"], ["beginner-friendly"]),
                ("Twin Islands", "Reef", "Intermediate", ["reef", "fish diversity"], []),
                ("Neill Island", "Shore", "Beginner", ["shore", "reef", "snorkel"], ["beginner-friendly"]),
                ("Havelock Elephant Beach", "Shore", "Beginner", ["beach", "reef fish", "snorkel"], ["beginner-friendly"]),
            ],
        },
        {
            "id": "indonesia-east-java",
            "name": "East Java & Madura",
            "country_id": "ID", "country": "Indonesia",
            "latitude": -7.5, "longitude": 113.5,
            "bounds": {"min_lat": -8.5, "max_lat": -6.5, "min_lon": 111.0, "max_lon": 115.5},
            "tagline": "Blue fire volcano dives and Java Sea reefs",
            "best_season": "April–November",
            "defaults": {
                "averageDepth": 12.0, "maxDepth": 22.0, "averageTemp": 27.0,
                "averageVisibility": 8.0, "difficulty": "Beginner",
                "curation_score": 7.8, "popularity_score": 7.0, "access_level": "boat",
            },
            "_sites": [
                ("Ijen Blue Fire Dive", "Shore", "Intermediate", ["volcanic crater", "blue fire", "extreme unique"], ["advanced-challenges"]),
                ("Gili Ketapang", "Reef", "Beginner", ["reef fish", "turtles", "shore"], ["beginner-friendly"]),
                ("Baluran National Park", "Shore", "Beginner", ["shore", "fish", "savanna backdrop"], ["beginner-friendly"]),
                ("Banyuwangi Reefs", "Reef", "Intermediate", ["reef", "fish diversity"], []),
                ("Kangean Islands", "Reef", "Intermediate", ["remote", "pristine", "reef fish"], []),
                ("Madura Strait", "Drift", "Intermediate", ["current", "fish", "macro"], []),
            ],
        },
    ],

    "micronesia": [
        {
            "id": "pohnpei-kosrae",
            "name": "Pohnpei & Kosrae, Micronesia",
            "country_id": "FM", "country": "Micronesia",
            "latitude": 6.8, "longitude": 158.2,
            "bounds": {"min_lat": 5.3, "max_lat": 7.5, "min_lon": 157.0, "max_lon": 163.5},
            "tagline": "Pristine mangrove reefs and untouched Micronesia",
            "best_season": "March–November",
            "defaults": {
                "averageDepth": 16.0, "maxDepth": 30.0, "averageTemp": 28.0,
                "averageVisibility": 20.0, "difficulty": "Intermediate",
                "curation_score": 8.5, "popularity_score": 6.5, "access_level": "boat",
            },
            "_sites": [
                ("Nan Madol Ancient City", "Reef", "Intermediate", ["ancient ruins", "reef fish", "unique"], []),
                ("Ant Atoll", "Reef", "Intermediate", ["remote atoll", "sharks", "reef fish"], ["big-animals"]),
                ("Pakin Atoll", "Reef", "Advanced", ["remote", "pristine", "sharks"], ["big-animals", "liveaboard"]),
                ("Kosrae Walung Wall", "Wall", "Intermediate", ["wall", "reef fish", "pristine"], []),
                ("Shark Island Pohnpei", "Reef", "Intermediate", ["reef sharks", "clear water", "fish"], ["big-animals"]),
                ("Manta Road", "Reef", "Intermediate", ["manta rays", "cleaning station"], ["big-animals"]),
                ("Finnmark Shoal", "Reef", "Advanced", ["remote", "pelagic", "sharks"], ["big-animals", "advanced-challenges"]),
            ],
        },
    ],

    "red-sea": [
        {
            "id": "aqaba-gulf",
            "name": "Aqaba & Gulf of Aqaba (Jordan & Saudi)",
            "country_id": "JO", "country": "Jordan",
            "latitude": 29.5, "longitude": 35.0,
            "bounds": {"min_lat": 28.5, "max_lat": 29.7, "min_lon": 34.7, "max_lon": 35.3},
            "tagline": "Compact but world-class reefs in Jordan's only sea",
            "best_season": "March–November",
            "defaults": {
                "averageDepth": 15.0, "maxDepth": 35.0, "averageTemp": 24.0,
                "averageVisibility": 20.0, "difficulty": "Beginner",
                "curation_score": 8.8, "popularity_score": 8.2, "access_level": "shore",
            },
            "_sites": [
                ("Cedar Pride Wreck", "Wreck", "Intermediate", ["Lebanese freighter wreck", "coral growth", "reef fish"], ["wreck-capitals"]),
                ("The Power Station", "Shore", "Beginner", ["shore", "reef fish", "coral"], ["beginner-friendly"]),
                ("First Bay", "Shore", "Beginner", ["coral garden", "reef fish", "shore"], ["beginner-friendly"]),
                ("Black Rock", "Reef", "Intermediate", ["reef", "reef fish", "macro"], []),
                ("The Tank", "Shore", "Beginner", ["tank wreck", "shallow", "reef fish"], ["wreck-capitals", "beginner-friendly"]),
                ("Japanese Garden", "Shore", "Beginner", ["coral garden", "turtles", "reef fish"], ["beginner-friendly"]),
                ("Blue Coral", "Shore", "Beginner", ["blue coral", "reef fish", "shallow"], ["beginner-friendly"]),
                ("Seven Sisters", "Shore", "Intermediate", ["reef formations", "fish"], []),
                ("Moon Valley", "Shore", "Beginner", ["sandy", "eels", "reef fish"], ["beginner-friendly"]),
                ("Oliver's Canyon", "Shore", "Intermediate", ["canyon", "macro", "reef fish"], []),
            ],
        },
        {
            "id": "sinai-north-red-sea",
            "name": "Tiran & Northern Sinai",
            "country_id": "EG", "country": "Egypt",
            "latitude": 28.0, "longitude": 34.55,
            "bounds": {"min_lat": 27.8, "max_lat": 28.3, "min_lon": 34.3, "max_lon": 34.8},
            "tagline": "Tiran Island straits and spectacular wall diving",
            "best_season": "March–May, October–November",
            "defaults": {
                "averageDepth": 18.0, "maxDepth": 40.0, "averageTemp": 25.0,
                "averageVisibility": 22.0, "difficulty": "Intermediate",
                "curation_score": 8.9, "popularity_score": 8.5, "access_level": "boat",
            },
            "_sites": [
                ("Woodhouse Reef", "Reef", "Advanced", ["strong current", "pelagic", "schooling fish"], ["big-animals", "advanced-challenges"]),
                ("Thomas Reef", "Reef", "Advanced", ["current", "wall", "fish density"], ["advanced-challenges"]),
                ("Gordon Reef", "Reef", "Intermediate", ["wreck on reef", "fish diversity", "current"], []),
                ("Jackson Reef", "Reef", "Advanced", ["northernmost Tiran reef", "current", "pelagic"], ["big-animals", "advanced-challenges"]),
                ("Laguna Reef", "Reef", "Intermediate", ["lagoon", "reef fish", "coral"], []),
                ("The Alternatives", "Reef", "Beginner", ["calm reef", "coral garden", "fish"], ["beginner-friendly"]),
                ("Na'ama Bay Reefs", "Shore", "Beginner", ["shore", "reef fish", "turtles"], ["beginner-friendly"]),
            ],
        },
    ],

    "maldives-indian-ocean": [
        {
            "id": "sri-lanka",
            "name": "Sri Lanka",
            "country_id": "LK", "country": "Sri Lanka",
            "latitude": 7.5, "longitude": 80.7,
            "bounds": {"min_lat": 5.9, "max_lat": 9.8, "min_lon": 79.5, "max_lon": 82.0},
            "tagline": "Whale watching, ancient wrecks, and tropical reefs",
            "best_season": "November–April (west); May–October (east)",
            "defaults": {
                "averageDepth": 15.0, "maxDepth": 30.0, "averageTemp": 28.0,
                "averageVisibility": 10.0, "difficulty": "Intermediate",
                "curation_score": 8.5, "popularity_score": 7.8, "access_level": "boat",
            },
            "_sites": [
                ("Hikkaduwa Marine Sanctuary", "Reef", "Beginner", ["protected reef", "turtles", "coral", "reef fish"], ["beginner-friendly"]),
                ("Bar Reef Sanctuary", "Reef", "Intermediate", ["protected", "pristine", "diverse fish"], []),
                ("SS Thermopylae Wreck", "Wreck", "Intermediate", ["historic wreck", "reef fish", "coral growth"], ["wreck-capitals"]),
                ("Beruwala Reefs", "Reef", "Beginner", ["coral garden", "reef fish"], ["beginner-friendly"]),
                ("Batticaloa Reef", "Reef", "Intermediate", ["east coast", "reef", "fish diversity"], []),
                ("Trincomalee Pigeon Island", "Reef", "Beginner", ["protected island", "blacktip sharks", "reef fish"], ["big-animals", "beginner-friendly"]),
                ("Great Basses Reef", "Reef", "Advanced", ["remote", "strong current", "whale sharks"], ["big-animals", "advanced-challenges"]),
                ("Little Basses Reef", "Reef", "Advanced", ["remote", "current", "pelagic"], ["big-animals", "advanced-challenges"]),
                ("Galle Wrecks", "Wreck", "Intermediate", ["multiple wrecks", "history", "reef fish"], ["wreck-capitals"]),
                ("Weligama Bay", "Shore", "Beginner", ["beginner friendly", "shore", "reef fish"], ["beginner-friendly"]),
                ("Unawatuna", "Shore", "Beginner", ["reef", "turtles", "shore"], ["beginner-friendly"]),
                ("Kalpitiya Mannar", "Reef", "Intermediate", ["reef", "dolphins", "whale watching"], ["big-animals"]),
            ],
        },
        {
            "id": "lakshadweep-india",
            "name": "Lakshadweep Islands, India",
            "country_id": "IN", "country": "India",
            "latitude": 10.6, "longitude": 72.6,
            "bounds": {"min_lat": 8.0, "max_lat": 12.5, "min_lon": 71.5, "max_lon": 74.0},
            "tagline": "Remote Indian Ocean atolls with pristine coral",
            "best_season": "November–April",
            "defaults": {
                "averageDepth": 16.0, "maxDepth": 30.0, "averageTemp": 28.0,
                "averageVisibility": 20.0, "difficulty": "Intermediate",
                "curation_score": 8.8, "popularity_score": 6.5, "access_level": "liveaboard",
            },
            "_sites": [
                ("Agatti Lagoon", "Reef", "Beginner", ["atoll lagoon", "reef fish", "turtles"], ["beginner-friendly"]),
                ("Bangaram Atoll", "Reef", "Intermediate", ["pristine atoll", "reef fish", "rays"], []),
                ("Suheli Par", "Reef", "Advanced", ["remote", "pristine", "large pelagic"], ["big-animals", "liveaboard"]),
                ("Kadmat Wall", "Wall", "Intermediate", ["atoll wall", "reef fish", "pelagic"], []),
                ("Minicoy Atoll", "Reef", "Advanced", ["remote", "pristine", "sharks"], ["big-animals", "liveaboard"]),
                ("Kavaratti Lagoon", "Reef", "Beginner", ["lagoon", "snorkel", "reef fish"], ["beginner-friendly"]),
                ("Kalpeni Atoll", "Reef", "Intermediate", ["atoll", "coral", "fish diversity"], []),
                ("Andretti Island", "Reef", "Advanced", ["remote", "untouched", "pelagic"], ["liveaboard", "advanced-challenges"]),
            ],
        },
    ],

    "east-africa-arabia": [
        {
            "id": "madagascar",
            "name": "Madagascar",
            "country_id": "MG", "country": "Madagascar",
            "latitude": -20.3, "longitude": 44.3,
            "bounds": {"min_lat": -25.5, "max_lat": -12.0, "min_lon": 43.0, "max_lon": 51.0},
            "tagline": "Humpback whales and untouched coral reefs",
            "best_season": "October–March (north); July–September (south)",
            "defaults": {
                "averageDepth": 16.0, "maxDepth": 30.0, "averageTemp": 27.0,
                "averageVisibility": 15.0, "difficulty": "Intermediate",
                "curation_score": 8.8, "popularity_score": 7.0, "access_level": "boat",
            },
            "_sites": [
                ("Nosy Be Reefs", "Reef", "Intermediate", ["reef fish", "whale sharks", "turtles"], ["big-animals"]),
                ("Nosy Iranja", "Reef", "Intermediate", ["pristine reef", "turtles", "dolphins"], ["big-animals"]),
                ("Radama Islands", "Reef", "Intermediate", ["remote", "reef fish", "pristine"], []),
                ("Banc du Leven", "Reef", "Advanced", ["remote", "pelagic", "sharks"], ["big-animals", "advanced-challenges"]),
                ("Sainte Marie Island", "Reef", "Intermediate", ["humpback whales", "reef fish", "turtles"], ["big-animals"]),
                ("Fort Dauphin Reefs", "Reef", "Advanced", ["remote", "strong current", "pristine"], ["advanced-challenges"]),
                ("Toliara Reef", "Reef", "Beginner", ["fringing reef", "reef fish", "coral"], ["beginner-friendly"]),
                ("Chesterfield Atoll", "Reef", "Advanced", ["very remote", "pristine", "sharks"], ["big-animals", "liveaboard", "advanced-challenges"]),
                ("Ifaty Reefs", "Reef", "Intermediate", ["reef", "fish diversity", "whale sharks seasonal"], ["big-animals"]),
                ("Ankivonjy Bay", "Reef", "Beginner", ["calm bay", "coral", "fish"], ["beginner-friendly"]),
            ],
        },
        {
            "id": "djibouti",
            "name": "Djibouti & Gulf of Aden",
            "country_id": "DJ", "country": "Djibouti",
            "latitude": 11.5, "longitude": 43.1,
            "bounds": {"min_lat": 11.0, "max_lat": 12.5, "min_lon": 42.5, "max_lon": 44.5},
            "tagline": "Whale sharks year-round and unique Red Sea meets",
            "best_season": "October–February (whale sharks)",
            "defaults": {
                "averageDepth": 15.0, "maxDepth": 30.0, "averageTemp": 28.0,
                "averageVisibility": 15.0, "difficulty": "Intermediate",
                "curation_score": 8.5, "popularity_score": 6.5, "access_level": "boat",
            },
            "_sites": [
                ("Seven Brothers Islands", "Reef", "Advanced", ["remote", "pristine", "hammerheads"], ["big-animals", "advanced-challenges"]),
                ("Whale Shark Bay Djibouti", "Reef", "Beginner", ["whale sharks", "snorkel", "surface"], ["big-animals", "beginner-friendly"]),
                ("Moucha Island", "Reef", "Beginner", ["reef fish", "coral", "snorkel"], ["beginner-friendly"]),
                ("Maskali Island", "Reef", "Intermediate", ["reef", "fish diversity"], []),
                ("Gulf of Tadjoura", "Reef", "Intermediate", ["reef", "whale sharks", "dolphins"], ["big-animals"]),
                ("Ras Ali", "Reef", "Intermediate", ["reef", "reef fish", "macro"], []),
            ],
        },
    ],

    "australia-new-zealand": [
        {
            "id": "lord-howe-norfolk",
            "name": "Lord Howe & Norfolk Islands",
            "country_id": "AU", "country": "Australia",
            "latitude": -31.5, "longitude": 159.1,
            "bounds": {"min_lat": -32.0, "max_lat": -28.5, "min_lon": 158.5, "max_lon": 167.0},
            "tagline": "UNESCO island with world's southernmost coral reef",
            "best_season": "January–April",
            "defaults": {
                "averageDepth": 15.0, "maxDepth": 30.0, "averageTemp": 22.0,
                "averageVisibility": 20.0, "difficulty": "Intermediate",
                "curation_score": 9.3, "popularity_score": 7.5, "access_level": "boat",
            },
            "_sites": [
                ("Admiralty Anchors Lord Howe", "Reef", "Intermediate", ["endemic fish", "clear water", "coral"], []),
                ("North Bay Lord Howe", "Shore", "Beginner", ["snorkel", "reef fish", "clear water"], ["beginner-friendly"]),
                ("Ball's Pyramid", "Reef", "Advanced", ["dramatic sea stack", "pelagic", "remote"], ["advanced-challenges"]),
                ("Malabar Reef", "Reef", "Intermediate", ["reef fish", "endemic species", "garouper"], []),
                ("Sylphs Hole", "Reef", "Intermediate", ["coral", "reef fish", "unique"], []),
                ("Comet Hole", "Reef", "Intermediate", ["reef", "fish", "clear water"], []),
                ("Sea Horse Paddock", "Shore", "Beginner", ["seahorses", "seagrass", "macro"], ["macro-muck", "beginner-friendly"]),
            ],
        },
        {
            "id": "south-australia-victoria",
            "name": "South Australia & Victoria",
            "country_id": "AU", "country": "Australia",
            "latitude": -35.0, "longitude": 138.0,
            "bounds": {"min_lat": -39.0, "max_lat": -32.0, "min_lon": 130.0, "max_lon": 150.0},
            "tagline": "Weedy sea dragons, giant cuttlefish, and cold southern reefs",
            "best_season": "October–April",
            "defaults": {
                "averageDepth": 12.0, "maxDepth": 25.0, "averageTemp": 16.0,
                "averageVisibility": 8.0, "difficulty": "Intermediate",
                "curation_score": 8.8, "popularity_score": 7.8, "access_level": "shore",
            },
            "_sites": [
                ("Rapid Bay Jetty", "Shore", "Intermediate", ["weedy sea dragons", "leafy sea dragons", "jetty"], ["macro-muck", "cold-water"]),
                ("HMAS Hobart Wreck", "Wreck", "Intermediate", ["navy destroyer", "artificial reef", "reef fish"], ["wreck-capitals"]),
                ("Port Noarlunga Reef", "Shore", "Beginner", ["protected reef", "shore", "fish"], ["beginner-friendly", "cold-water"]),
                ("Edithburgh Jetty", "Shore", "Beginner", ["jetty", "macro", "sea dragons"], ["macro-muck", "beginner-friendly"]),
                ("Whyalla Cuttlefish", "Shore", "Beginner", ["giant cuttlefish aggregation", "unique", "macro"], ["big-animals", "beginner-friendly"]),
                ("HMAS Canberra Wreck", "Wreck", "Intermediate", ["aircraft carrier wreck", "reef fish"], ["wreck-capitals"]),
                ("Wilsons Promontory", "Shore", "Intermediate", ["marine park", "seals", "reef fish"], ["big-animals", "cold-water"]),
                ("Lonsdale Wall", "Wall", "Advanced", ["current", "kelp", "fish density"], ["cold-water", "advanced-challenges"]),
                ("Mornington Peninsula", "Shore", "Intermediate", ["shore", "seals", "reef fish"], ["big-animals"]),
                ("Rye Pier", "Shore", "Beginner", ["pier", "macro", "night diving"], ["macro-muck", "beginner-friendly"]),
                ("Blairgowrie Pier", "Shore", "Beginner", ["weedy sea dragons", "macro", "pier"], ["macro-muck", "beginner-friendly"]),
            ],
        },
        {
            "id": "vanuatu",
            "name": "Vanuatu",
            "country_id": "VU", "country": "Vanuatu",
            "latitude": -16.0, "longitude": 168.3,
            "bounds": {"min_lat": -20.5, "max_lat": -13.0, "min_lon": 166.5, "max_lon": 170.5},
            "tagline": "SS President Coolidge — world's most accessible large wreck",
            "best_season": "May–October",
            "defaults": {
                "averageDepth": 18.0, "maxDepth": 35.0, "averageTemp": 27.0,
                "averageVisibility": 20.0, "difficulty": "Intermediate",
                "curation_score": 9.1, "popularity_score": 8.0, "access_level": "shore",
            },
            "_sites": [
                ("SS President Coolidge", "Wreck", "Intermediate", ["massive WWII wreck", "shore entry", "history", "artifacts"], ["wreck-capitals"]),
                ("Million Dollar Point", "Shore", "Beginner", ["WWII equipment dump", "reef fish", "coral growth"], ["wreck-capitals", "beginner-friendly"]),
                ("Tutuba Island", "Reef", "Intermediate", ["pristine reef", "reef fish", "coral"], []),
                ("Aore Island", "Reef", "Intermediate", ["reef", "fish diversity"], []),
                ("Hideaway Island", "Shore", "Beginner", ["marine sanctuary", "snorkel", "reef fish"], ["beginner-friendly"]),
                ("Paul's Rock", "Reef", "Advanced", ["current", "sharks", "pelagic"], ["big-animals", "advanced-challenges"]),
                ("Nambas Reef Malekula", "Reef", "Advanced", ["remote", "pristine", "reef fish"], ["liveaboard"]),
                ("Champagne Beach Reef", "Shore", "Beginner", ["shore", "reef fish", "snorkel"], ["beginner-friendly"]),
                ("Tanna Volcanic Reef", "Reef", "Intermediate", ["volcanic island", "unique", "reef fish"], []),
            ],
        },
    ],

    "pacific-islands": [
        {
            "id": "tonga",
            "name": "Tonga & Kingdom of Humpbacks",
            "country_id": "TO", "country": "Tonga",
            "latitude": -21.2, "longitude": -175.2,
            "bounds": {"min_lat": -23.5, "max_lat": -15.5, "min_lon": -177.0, "max_lon": -173.5},
            "tagline": "Swim with humpback whales — world's best",
            "best_season": "July–October (humpbacks)",
            "defaults": {
                "averageDepth": 15.0, "maxDepth": 30.0, "averageTemp": 26.0,
                "averageVisibility": 22.0, "difficulty": "Intermediate",
                "curation_score": 9.2, "popularity_score": 8.5, "access_level": "boat",
            },
            "_sites": [
                ("Humpback Whale Swim Vava'u", "Reef", "Beginner", ["humpback whales", "snorkel swim", "seasonal"], ["big-animals", "beginner-friendly"]),
                ("Mariners Cave", "Cave", "Advanced", ["no light entrance", "adventure cave", "unique"], ["caves-cenotes", "advanced-challenges"]),
                ("Swallows Cave Vava'u", "Cave", "Beginner", ["cavern", "light rays", "reef fish"], ["caves-cenotes", "beginner-friendly"]),
                ("Coral Gardens Tonga", "Reef", "Beginner", ["coral", "reef fish", "turtles"], ["beginner-friendly"]),
                ("Euakafa Island", "Reef", "Intermediate", ["pristine reef", "fish diversity"], []),
                ("Late Island", "Reef", "Advanced", ["remote", "pristine", "sharks"], ["big-animals", "liveaboard"]),
                ("Nuku Atoll", "Reef", "Advanced", ["remote atoll", "pelagic", "sharks"], ["big-animals", "liveaboard"]),
                ("Ha'apai Group", "Reef", "Intermediate", ["remote", "reef fish", "humpbacks"], ["big-animals"]),
                ("Tofua Volcano", "Reef", "Advanced", ["volcanic island", "remote", "unique"], ["advanced-challenges"]),
            ],
        },
        {
            "id": "niue",
            "name": "Niue — Rock of Polynesia",
            "country_id": "NU", "country": "Niue",
            "latitude": -19.0, "longitude": -169.9,
            "bounds": {"min_lat": -19.2, "max_lat": -18.8, "min_lon": -170.1, "max_lon": -169.7},
            "tagline": "Insanely clear visibility and sea snake encounters",
            "best_season": "May–October",
            "defaults": {
                "averageDepth": 16.0, "maxDepth": 35.0, "averageTemp": 25.0,
                "averageVisibility": 50.0, "difficulty": "Intermediate",
                "curation_score": 9.3, "popularity_score": 7.0, "access_level": "shore",
            },
            "_sites": [
                ("Limu Pools", "Shore", "Beginner", ["crystal clear", "reef fish", "sea snakes"], ["beginner-friendly"]),
                ("Ana Mahaga Cave", "Cave", "Intermediate", ["underwater cave", "sea snakes", "crystal clear"], ["caves-cenotes"]),
                ("The Chimney Niue", "Cave", "Intermediate", ["cavern", "unique", "sea snakes"], ["caves-cenotes"]),
                ("Bubble Cave", "Cave", "Beginner", ["air pocket cave", "unique", "reef fish"], ["caves-cenotes", "beginner-friendly"]),
                ("Snake Gully", "Shore", "Intermediate", ["sea snakes", "unique encounter", "clear water"], []),
                ("Hio Trench", "Wall", "Advanced", ["wall", "clear water", "pelagic"], ["advanced-challenges"]),
                ("Alofi Reef", "Shore", "Beginner", ["shore", "reef fish", "snorkel"], ["beginner-friendly"]),
            ],
        },
        {
            "id": "cook-islands-samoa",
            "name": "Cook Islands & Samoa",
            "country_id": "CK", "country": "Cook Islands",
            "latitude": -21.2, "longitude": -159.8,
            "bounds": {"min_lat": -22.5, "max_lat": -8.0, "min_lon": -172.0, "max_lon": -157.0},
            "tagline": "Pristine Polynesian reefs and turtles",
            "best_season": "April–November",
            "defaults": {
                "averageDepth": 15.0, "maxDepth": 30.0, "averageTemp": 26.0,
                "averageVisibility": 22.0, "difficulty": "Intermediate",
                "curation_score": 8.8, "popularity_score": 7.5, "access_level": "boat",
            },
            "_sites": [
                ("Rarotonga Reef", "Reef", "Beginner", ["fringing reef", "turtles", "reef fish"], ["beginner-friendly"]),
                ("Avarua Passage", "Drift", "Intermediate", ["channel", "current", "fish diversity"], []),
                ("Aitutaki Lagoon", "Reef", "Beginner", ["world's most beautiful lagoon", "snorkel", "reef fish"], ["beginner-friendly"]),
                ("Suwarrow Atoll", "Reef", "Advanced", ["remote UNESCO", "sharks", "pristine", "pelagic"], ["big-animals", "liveaboard", "advanced-challenges"]),
                ("Palmerston Atoll", "Reef", "Advanced", ["remote", "pristine", "sharks"], ["big-animals", "liveaboard"]),
                ("American Samoa", "Reef", "Intermediate", ["protected national park", "reef fish", "coral"], []),
                ("Fagatele Bay NMS", "Reef", "Intermediate", ["national marine sanctuary", "coral", "fish diversity"], []),
                ("To Sua Ocean Trench", "Cave", "Intermediate", ["natural pool", "cavern", "unique"], ["caves-cenotes"]),
            ],
        },
    ],

    "caribbean-atlantic": [
        {
            "id": "jamaica-barbados",
            "name": "Jamaica, Barbados & Lesser Antilles",
            "country_id": "JM", "country": "Jamaica",
            "latitude": 17.9, "longitude": -76.8,
            "bounds": {"min_lat": 12.0, "max_lat": 18.5, "min_lon": -80.0, "max_lon": -59.0},
            "tagline": "Coral-draped wrecks and drift dives in the eastern Caribbean",
            "best_season": "November–April",
            "defaults": {
                "averageDepth": 14.0, "maxDepth": 28.0, "averageTemp": 27.0,
                "averageVisibility": 20.0, "difficulty": "Beginner",
                "curation_score": 8.5, "popularity_score": 8.0, "access_level": "boat",
            },
            "_sites": [
                ("Montego Bay Marine Park", "Reef", "Beginner", ["protected reef", "reef fish", "turtles"], ["beginner-friendly"]),
                ("The Cathedrale Jamaica", "Cave", "Intermediate", ["cavern", "sponges", "reef fish"], ["caves-cenotes"]),
                ("Widowmaker's Cave", "Cave", "Intermediate", ["cavern", "reef fish", "sponges"], ["caves-cenotes"]),
                ("Mushroom Reef Jamaica", "Reef", "Beginner", ["coral", "reef fish", "turtles"], ["beginner-friendly"]),
                ("Shark Reef Jamaica", "Reef", "Intermediate", ["nurse sharks", "reef fish"], ["big-animals"]),
                ("Stavronikita Wreck Barbados", "Wreck", "Intermediate", ["130m freighter wreck", "coral", "reef fish"], ["wreck-capitals"]),
                ("Carlisle Bay Barbados", "Reef", "Beginner", ["multiple wrecks", "reef fish", "calm bay"], ["wreck-capitals", "beginner-friendly"]),
                ("Dome Barbados", "Reef", "Intermediate", ["concrete dome", "reef fish", "artificial reef"], ["beginner-friendly"]),
                ("Dominica Champagne Reef", "Shore", "Beginner", ["volcanic bubbles", "unique", "reef fish"], ["beginner-friendly"]),
                ("L'Abyme Dominica", "Shore", "Intermediate", ["critter diving", "macro", "unique fauna"], ["macro-muck"]),
                ("Soufrière Pinnacles Dominica", "Wall", "Intermediate", ["pinnacles", "wall", "fish"], []),
                ("Pitons St. Lucia", "Reef", "Intermediate", ["volcanic pinnacles", "reef fish", "UNESCO"], []),
                ("Anse Chastanet St. Lucia", "Shore", "Beginner", ["shore", "coral", "reef fish"], ["beginner-friendly"]),
                ("Tobago Speyside", "Reef", "Advanced", ["schooling fish", "manta rays", "current"], ["big-animals", "advanced-challenges"]),
                ("Nylon Pool Tobago", "Reef", "Beginner", ["shallow sandbar", "reef fish", "snorkel"], ["beginner-friendly"]),
            ],
        },
        {
            "id": "virgin-islands-usvi-bvi",
            "name": "US & British Virgin Islands",
            "country_id": "VI", "country": "US Virgin Islands",
            "latitude": 18.35, "longitude": -64.9,
            "bounds": {"min_lat": 17.8, "max_lat": 18.7, "min_lon": -65.5, "max_lon": -64.3},
            "tagline": "RMS Rhone — the Caribbean's most famous wreck",
            "best_season": "November–June",
            "defaults": {
                "averageDepth": 14.0, "maxDepth": 28.0, "averageTemp": 27.0,
                "averageVisibility": 22.0, "difficulty": "Beginner",
                "curation_score": 8.8, "popularity_score": 8.5, "access_level": "boat",
            },
            "_sites": [
                ("RMS Rhone Wreck", "Wreck", "Intermediate", ["Victorian mail ship", "iconic wreck", "coral growth"], ["wreck-capitals"]),
                ("The Chimney BVI", "Reef", "Beginner", ["swimthrough", "reef fish", "coral"], ["beginner-friendly"]),
                ("Alice in Wonderland", "Reef", "Beginner", ["mushroom coral", "reef fish"], ["beginner-friendly"]),
                ("The Indians", "Reef", "Beginner", ["pinnacles", "reef fish", "snorkel"], ["beginner-friendly"]),
                ("Blonde Rock", "Reef", "Intermediate", ["reef", "reef fish", "barracuda"], []),
                ("Carrot Shoal", "Reef", "Beginner", ["soft coral", "reef fish"], ["beginner-friendly"]),
                ("Buck Island USVI", "Reef", "Beginner", ["national monument", "elkhorn coral", "turtles"], ["beginner-friendly"]),
                ("Cane Bay Wall USVI", "Wall", "Intermediate", ["steep wall", "sponges", "fish"], []),
                ("The Wall St. Croix", "Wall", "Intermediate", ["vertical wall", "reef fish"], []),
                ("Salt River Canyon", "Wall", "Advanced", ["canyon walls", "pelagic", "deep"], ["advanced-challenges"]),
            ],
        },
        {
            "id": "curacao-aruba",
            "name": "Curaçao, Aruba & Dutch Caribbean",
            "country_id": "CW", "country": "Curaçao",
            "latitude": 12.2, "longitude": -68.9,
            "bounds": {"min_lat": 12.0, "max_lat": 12.8, "min_lon": -70.1, "max_lon": -68.7},
            "tagline": "Wall diving and colorful Dutch island reefs",
            "best_season": "Year-round",
            "defaults": {
                "averageDepth": 15.0, "maxDepth": 35.0, "averageTemp": 27.0,
                "averageVisibility": 22.0, "difficulty": "Beginner",
                "curation_score": 8.8, "popularity_score": 8.5, "access_level": "shore",
            },
            "_sites": [
                ("Mushroom Forest Curacao", "Reef", "Intermediate", ["giant star coral formations", "unique", "reef fish"], []),
                ("Director's Bay", "Shore", "Beginner", ["shore", "seahorse", "macro", "reef fish"], ["macro-muck", "beginner-friendly"]),
                ("Playa Kalki", "Shore", "Beginner", ["shore", "wall", "reef fish"], ["beginner-friendly"]),
                ("Watamula Curacao", "Wall", "Advanced", ["strong current", "wall", "pelagic"], ["advanced-challenges"]),
                ("Tugboat Curacao", "Wreck", "Beginner", ["shallow wreck", "reef fish", "coral growth"], ["wreck-capitals", "beginner-friendly"]),
                ("Blue Room Curacao", "Cave", "Beginner", ["blue light cave", "unique", "fish"], ["caves-cenotes", "beginner-friendly"]),
                ("Antilla Wreck Aruba", "Wreck", "Intermediate", ["largest Caribbean wreck", "WWII", "coral growth"], ["wreck-capitals"]),
                ("Shark's Cove Aruba", "Reef", "Intermediate", ["nurse sharks", "reef fish"], ["big-animals"]),
                ("California Wreck Aruba", "Wreck", "Intermediate", ["historic wreck", "reef fish"], ["wreck-capitals"]),
                ("Barracuda's Reef Aruba", "Reef", "Beginner", ["barracuda", "reef fish", "coral"], ["beginner-friendly"]),
            ],
        },
    ],

    "mediterranean-europe": [
        {
            "id": "greece-aegean",
            "name": "Greece & Aegean Islands",
            "country_id": "GR", "country": "Greece",
            "latitude": 37.5, "longitude": 24.5,
            "bounds": {"min_lat": 35.0, "max_lat": 41.0, "min_lon": 20.0, "max_lon": 29.0},
            "tagline": "Ancient wrecks, caves, and the cradle of civilization",
            "best_season": "May–October",
            "defaults": {
                "averageDepth": 15.0, "maxDepth": 35.0, "averageTemp": 22.0,
                "averageVisibility": 20.0, "difficulty": "Intermediate",
                "curation_score": 8.5, "popularity_score": 8.0, "access_level": "boat",
            },
            "_sites": [
                ("Mykonos Wrecks", "Wreck", "Intermediate", ["wrecks", "reef fish", "history"], ["wreck-capitals"]),
                ("Delos Marine Park", "Reef", "Intermediate", ["protected", "reef fish", "ancient ruins nearby"], []),
                ("Santorini Caldera", "Reef", "Intermediate", ["volcanic caldera", "unique", "reef fish"], []),
                ("Epidaurus Reef", "Reef", "Beginner", ["reef fish", "octopus", "macro"], ["beginner-friendly"]),
                ("Kassos Island", "Reef", "Advanced", ["current", "pelagic", "reef fish"], ["advanced-challenges"]),
                ("Alonnisos Marine Park", "Reef", "Intermediate", ["protected marine park", "grouper", "reef fish"], []),
                ("Rhodes Wrecks", "Wreck", "Intermediate", ["historic wrecks", "reef fish"], ["wreck-capitals"]),
                ("Spetses Reef", "Reef", "Beginner", ["reef fish", "octopus", "macro"], ["beginner-friendly"]),
                ("Lefkada Caves", "Cave", "Intermediate", ["cave system", "reef fish", "blue light"], ["caves-cenotes"]),
                ("Kefalonia Blue Caves", "Cave", "Beginner", ["blue cave", "snorkel", "unique"], ["caves-cenotes", "beginner-friendly"]),
                ("Zakynthos Turtles", "Shore", "Beginner", ["loggerhead turtles", "nesting beach", "reef fish"], ["big-animals", "beginner-friendly"]),
                ("Crete Wrecks", "Wreck", "Intermediate", ["WWII wrecks", "reef fish", "history"], ["wreck-capitals"]),
            ],
        },
        {
            "id": "spain-balearics",
            "name": "Spain, Balearic Islands & Costa Brava",
            "country_id": "ES", "country": "Spain",
            "latitude": 39.5, "longitude": 2.5,
            "bounds": {"min_lat": 36.0, "max_lat": 43.5, "min_lon": -2.0, "max_lon": 5.0},
            "tagline": "Posidonia meadows and marine reserves",
            "best_season": "May–October",
            "defaults": {
                "averageDepth": 14.0, "maxDepth": 35.0, "averageTemp": 20.0,
                "averageVisibility": 18.0, "difficulty": "Beginner",
                "curation_score": 8.2, "popularity_score": 8.0, "access_level": "boat",
            },
            "_sites": [
                ("Medes Islands Reserve", "Reef", "Intermediate", ["marine reserve", "grouper", "reef fish"], []),
                ("Ses Salines Ibiza", "Reef", "Beginner", ["posidonia meadows", "reef fish", "clear water"], ["beginner-friendly"]),
                ("Cala de Sant Vicenç", "Cave", "Intermediate", ["caves", "reef fish", "macro"], ["caves-cenotes"]),
                ("Cap de Creus", "Reef", "Intermediate", ["marine reserve", "fish diversity", "current"], []),
                ("Palamos Reef", "Reef", "Intermediate", ["reef", "octopus", "fish"], []),
                ("Mallorca Wrecks", "Wreck", "Intermediate", ["wrecks", "reef fish", "history"], ["wreck-capitals"]),
                ("Menorca Caves", "Cave", "Beginner", ["sea caves", "reef fish", "blue light"], ["caves-cenotes", "beginner-friendly"]),
                ("Murcia Mar Menor", "Shore", "Beginner", ["inland sea", "unique", "shore"], ["beginner-friendly"]),
                ("Almeria Cape", "Reef", "Intermediate", ["marine reserve", "grouper", "reef fish"], []),
                ("Las Negras", "Shore", "Beginner", ["shore", "reef fish", "macro"], ["beginner-friendly"]),
            ],
        },
        {
            "id": "turkey-mediterranean",
            "name": "Turkey — Aegean & Mediterranean",
            "country_id": "TR", "country": "Turkey",
            "latitude": 37.0, "longitude": 28.0,
            "bounds": {"min_lat": 36.0, "max_lat": 38.5, "min_lon": 26.5, "max_lon": 36.5},
            "tagline": "Ancient wrecks and spectacular Aegean reefs",
            "best_season": "May–November",
            "defaults": {
                "averageDepth": 15.0, "maxDepth": 35.0, "averageTemp": 22.0,
                "averageVisibility": 18.0, "difficulty": "Beginner",
                "curation_score": 8.3, "popularity_score": 7.8, "access_level": "boat",
            },
            "_sites": [
                ("Olu Deniz Blue Lagoon", "Reef", "Beginner", ["lagoon", "reef fish", "scenic"], ["beginner-friendly"]),
                ("Bodrum Wrecks", "Wreck", "Intermediate", ["historic wrecks", "reef fish", "sponges"], ["wreck-capitals"]),
                ("Kalkan Reefs", "Reef", "Intermediate", ["reef", "reef fish", "octopus"], []),
                ("Kas Caves", "Cave", "Intermediate", ["caves", "reef fish", "macro"], ["caves-cenotes"]),
                ("Gokova Bay", "Reef", "Intermediate", ["marine sanctuary", "grouper", "reef fish"], []),
                ("Kekova Sunken City", "Reef", "Beginner", ["sunken ruins", "reef fish", "history"], ["beginner-friendly"]),
                ("Datca Peninsula", "Reef", "Intermediate", ["marine reserve", "reef fish", "clear water"], []),
                ("Izmir Bay", "Reef", "Intermediate", ["reef", "octopus", "macro"], []),
                ("Cesme Wrecks", "Wreck", "Intermediate", ["wrecks", "reef fish"], ["wreck-capitals"]),
                ("Marmaris Reefs", "Reef", "Beginner", ["reef", "reef fish", "coral"], ["beginner-friendly"]),
            ],
        },
        {
            "id": "italy-sicily",
            "name": "Italy, Sicily & Sardinia",
            "country_id": "IT", "country": "Italy",
            "latitude": 38.0, "longitude": 14.5,
            "bounds": {"min_lat": 36.5, "max_lat": 41.5, "min_lon": 8.0, "max_lon": 16.5},
            "tagline": "Wrecks, sea caves, and Mediterranean reefs",
            "best_season": "June–October",
            "defaults": {
                "averageDepth": 14.0, "maxDepth": 35.0, "averageTemp": 22.0,
                "averageVisibility": 15.0, "difficulty": "Intermediate",
                "curation_score": 8.2, "popularity_score": 7.8, "access_level": "boat",
            },
            "_sites": [
                ("Ustica Marine Reserve", "Reef", "Intermediate", ["first Italian marine reserve", "grouper", "fish diversity"], []),
                ("Tremiti Islands", "Reef", "Intermediate", ["marine reserve", "reef fish", "posidonia"], []),
                ("Ischia Thermal Reefs", "Reef", "Beginner", ["thermal vents", "unique", "reef fish"], ["beginner-friendly"]),
                ("Capri Faraglioni", "Reef", "Beginner", ["rocky stacks", "reef fish", "scenic"], ["beginner-friendly"]),
                ("Elba Island", "Reef", "Intermediate", ["reef", "reef fish", "wrecks"], ["wreck-capitals"]),
                ("SS Chrisso Wreck Sardinia", "Wreck", "Intermediate", ["wreck", "reef fish"], ["wreck-capitals"]),
                ("Sardinia Caves", "Cave", "Intermediate", ["sea caves", "reef fish", "posidonia"], ["caves-cenotes"]),
                ("Taormina Sicily", "Reef", "Beginner", ["reef", "reef fish", "macro"], ["beginner-friendly"]),
                ("Strait of Messina", "Drift", "Advanced", ["extreme current", "fish density", "unique"], ["advanced-challenges"]),
                ("Lampedusa Island", "Reef", "Advanced", ["remote", "pristine", "loggerhead turtles"], ["big-animals"]),
            ],
        },
    ],

    "central-america-mexico-pacific": [
        {
            "id": "colombian-caribbean",
            "name": "Colombian Caribbean — Rosario & San Andrés",
            "country_id": "CO", "country": "Colombia",
            "latitude": 13.4, "longitude": -81.7,
            "bounds": {"min_lat": 9.0, "max_lat": 15.0, "min_lon": -83.0, "max_lon": -74.0},
            "tagline": "Pristine Caribbean reefs and UNESCO biosphere",
            "best_season": "January–April, July–August",
            "defaults": {
                "averageDepth": 14.0, "maxDepth": 28.0, "averageTemp": 27.0,
                "averageVisibility": 20.0, "difficulty": "Beginner",
                "curation_score": 8.5, "popularity_score": 7.5, "access_level": "boat",
            },
            "_sites": [
                ("Old Providence Island", "Reef", "Advanced", ["3rd largest barrier reef", "sharks", "pristine"], ["big-animals", "advanced-challenges"]),
                ("San Andrés El Cañon", "Reef", "Intermediate", ["canyon", "reef fish", "coral"], []),
                ("Islas del Rosario", "Reef", "Beginner", ["protected island park", "reef fish", "coral"], ["beginner-friendly"]),
                ("El Planchon", "Reef", "Intermediate", ["reef", "sharks", "fish diversity"], ["big-animals"]),
                ("Capurgana Reefs", "Reef", "Intermediate", ["remote", "pristine reef", "fish"], []),
                ("La Piscina", "Shore", "Beginner", ["shallow reef", "shore", "reef fish"], ["beginner-friendly"]),
                ("Titiribí", "Reef", "Intermediate", ["reef", "fish diversity", "macro"], []),
                ("Blue Diamond", "Reef", "Intermediate", ["reef", "coral", "fish"], []),
            ],
        },
        {
            "id": "ecuador-peru-pacific",
            "name": "Ecuador & Peru Coast",
            "country_id": "EC", "country": "Ecuador",
            "latitude": -2.5, "longitude": -80.5,
            "bounds": {"min_lat": -12.0, "max_lat": 2.0, "min_lon": -82.0, "max_lon": -77.0},
            "tagline": "Hammerheads, whale sharks, and Pacific diversity",
            "best_season": "December–May",
            "defaults": {
                "averageDepth": 16.0, "maxDepth": 30.0, "averageTemp": 22.0,
                "averageVisibility": 10.0, "difficulty": "Intermediate",
                "curation_score": 8.5, "popularity_score": 7.0, "access_level": "boat",
            },
            "_sites": [
                ("Machalilla National Park", "Reef", "Intermediate", ["protected", "reef fish", "humpback whales seasonal"], ["big-animals"]),
                ("Islote El Pelado", "Reef", "Intermediate", ["marine reserve", "reef fish", "sharks"], ["big-animals"]),
                ("Paita Reef Peru", "Reef", "Advanced", ["cold current", "sea lions", "unique fauna"], ["big-animals", "cold-water", "advanced-challenges"]),
                ("Lobos de Tierra", "Reef", "Advanced", ["sea lions", "fur seals", "cold Pacific"], ["big-animals", "advanced-challenges"]),
                ("Islas Lobos Ecuador", "Shore", "Intermediate", ["sea lions", "reef fish", "current"], ["big-animals"]),
            ],
        },
    ],

    "south-america": [
        {
            "id": "colombia-venezuela-caribbean",
            "name": "Colombia & Venezuela Caribbean",
            "country_id": "CO", "country": "Colombia",
            "latitude": 11.0, "longitude": -72.0,
            "bounds": {"min_lat": 10.0, "max_lat": 12.5, "min_lon": -75.0, "max_lon": -60.0},
            "tagline": "Pristine Caribbean reefs from Tayrona to Morrocoy",
            "best_season": "December–April",
            "defaults": {
                "averageDepth": 14.0, "maxDepth": 28.0, "averageTemp": 28.0,
                "averageVisibility": 15.0, "difficulty": "Intermediate",
                "curation_score": 8.3, "popularity_score": 7.0, "access_level": "boat",
            },
            "_sites": [
                ("Tayrona Park Reefs", "Reef", "Intermediate", ["national park", "reef fish", "coral"], []),
                ("Bahía Concha", "Shore", "Beginner", ["protected bay", "reef fish", "snorkel"], ["beginner-friendly"]),
                ("Islas del Rosario Deep", "Reef", "Advanced", ["outer reef", "sharks", "pelagic"], ["big-animals", "advanced-challenges"]),
                ("Morrocoy National Park", "Reef", "Beginner", ["protected", "coral gardens", "mangrove"], ["beginner-friendly"]),
                ("Los Roques Archipelago", "Reef", "Intermediate", ["UNESCO", "remote", "pristine reef"], []),
                ("Gran Roque Outer Wall", "Wall", "Advanced", ["wall", "pelagic", "sharks"], ["big-animals", "advanced-challenges"]),
                ("La Tortuga Island", "Reef", "Intermediate", ["turtles", "pristine", "reef fish"], ["big-animals"]),
                ("Las Aves Archipelago", "Reef", "Advanced", ["remote", "pristine atoll", "pelagic"], ["big-animals", "liveaboard"]),
            ],
        },
        {
            "id": "brazil-northeast",
            "name": "Northeast Brazil — Abrolhos & Recife",
            "country_id": "BR", "country": "Brazil",
            "latitude": -9.0, "longitude": -35.5,
            "bounds": {"min_lat": -20.0, "max_lat": -5.0, "min_lon": -39.5, "max_lon": -32.0},
            "tagline": "Humpback whales, endemic fish, and unique Brazilian reefs",
            "best_season": "July–November (humpbacks); Year-round (Recife)",
            "defaults": {
                "averageDepth": 14.0, "maxDepth": 25.0, "averageTemp": 27.0,
                "averageVisibility": 12.0, "difficulty": "Intermediate",
                "curation_score": 8.5, "popularity_score": 7.5, "access_level": "boat",
            },
            "_sites": [
                ("Abrolhos Archipelago", "Reef", "Intermediate", ["humpback whales", "cabeços coral", "endemic fish"], ["big-animals"]),
                ("Parcel das Paredes", "Reef", "Advanced", ["offshore reef", "sharks", "pelagic"], ["big-animals", "advanced-challenges"]),
                ("Porto de Galinhas Pools", "Shore", "Beginner", ["natural tidal pools", "reef fish", "snorkel"], ["beginner-friendly"]),
                ("Recife Reefs", "Reef", "Intermediate", ["fringing reef", "reef fish", "sharks"], ["big-animals"]),
                ("Maracajaú Parrachos", "Reef", "Beginner", ["tidal reef", "reef fish", "snorkel"], ["beginner-friendly"]),
                ("Picasso Rock", "Reef", "Intermediate", ["reef", "fish diversity", "macro"], []),
                ("Atol das Rocas", "Reef", "Advanced", ["UNESCO biosphere", "sharks", "remote", "pristine"], ["big-animals", "liveaboard", "advanced-challenges"]),
                ("Saco do Céu", "Shore", "Beginner", ["bay", "calm", "reef fish"], ["beginner-friendly"]),
                ("Búzios Reefs", "Reef", "Intermediate", ["reef", "fish diversity", "clear water"], []),
            ],
        },
    ],

    "cold-water-north-atlantic": [
        {
            "id": "ireland-west-coast",
            "name": "Ireland & West Coast",
            "country_id": "IE", "country": "Ireland",
            "latitude": 53.5, "longitude": -9.5,
            "bounds": {"min_lat": 51.0, "max_lat": 55.5, "min_lon": -11.0, "max_lon": -6.0},
            "tagline": "Basking sharks, seals, and stunning Atlantic wrecks",
            "best_season": "May–September",
            "defaults": {
                "averageDepth": 12.0, "maxDepth": 25.0, "averageTemp": 12.0,
                "averageVisibility": 8.0, "difficulty": "Intermediate",
                "curation_score": 8.5, "popularity_score": 6.8, "access_level": "boat",
            },
            "_sites": [
                ("SS Laurentic Wreck", "Wreck", "Intermediate", ["WWII wreck with gold", "history", "cold water"], ["wreck-capitals", "cold-water"]),
                ("MV Plassy Aran Islands", "Wreck", "Beginner", ["famous stranded ship", "shore viewing", "reef fish"], ["wreck-capitals"]),
                ("Killary Fjord", "Reef", "Intermediate", ["fjord", "kelp", "cold water", "seals"], ["cold-water"]),
                ("Clare Island", "Shore", "Intermediate", ["seals", "cold water", "reef fish"], ["big-animals", "cold-water"]),
                ("Blasket Islands", "Reef", "Advanced", ["remote", "basking sharks", "seals"], ["big-animals", "cold-water", "advanced-challenges"]),
                ("Old Head of Kinsale", "Reef", "Intermediate", ["reef", "cold water", "fish diversity"], ["cold-water"]),
                ("Sherkin Island", "Shore", "Intermediate", ["shore diving", "kelp", "reef fish"], ["cold-water"]),
                ("Malin Head", "Shore", "Advanced", ["northernmost point", "current", "cold water"], ["cold-water", "advanced-challenges"]),
            ],
        },
        {
            "id": "south-africa-cold-atlantic",
            "name": "Antarctica & Sub-Antarctic",
            "country_id": "AQ", "country": "Antarctica",
            "latitude": -63.0, "longitude": -57.0,
            "bounds": {"min_lat": -75.0, "max_lat": -55.0, "min_lon": -90.0, "max_lon": -20.0},
            "tagline": "The ultimate cold-water frontier — icebergs and leopard seals",
            "best_season": "December–February (southern summer)",
            "defaults": {
                "averageDepth": 12.0, "maxDepth": 20.0, "averageTemp": 0.0,
                "averageVisibility": 15.0, "difficulty": "Advanced",
                "curation_score": 9.5, "popularity_score": 5.0, "access_level": "liveaboard",
            },
            "_sites": [
                ("Half Moon Island", "Reef", "Advanced", ["penguins", "leopard seals", "iceberg backdrop"], ["big-animals", "cold-water", "liveaboard", "advanced-challenges"]),
                ("Deception Island", "Reef", "Advanced", ["volcanic caldera", "penguins", "extreme cold"], ["cold-water", "liveaboard", "advanced-challenges"]),
                ("Enterprise Island", "Wreck", "Advanced", ["frozen ship wreck", "unique", "cold water"], ["wreck-capitals", "cold-water", "liveaboard", "advanced-challenges"]),
                ("Whalers Bay", "Shore", "Advanced", ["historic whaling station", "cold water", "unique"], ["cold-water", "advanced-challenges"]),
                ("South Georgia Island", "Reef", "Advanced", ["elephant seals", "leopard seals", "remote"], ["big-animals", "cold-water", "liveaboard", "advanced-challenges"]),
            ],
        },
    ],

    "japan-east-asia": [
        {
            "id": "hokkaido-northern-japan",
            "name": "Hokkaido & Northern Japan",
            "country_id": "JP", "country": "Japan",
            "latitude": 43.5, "longitude": 141.5,
            "bounds": {"min_lat": 41.5, "max_lat": 45.5, "min_lon": 139.0, "max_lon": 145.5},
            "tagline": "Ice diving, sea angels, and cold Pacific critters",
            "best_season": "January–April (ice); June–October (warmer)",
            "defaults": {
                "averageDepth": 12.0, "maxDepth": 25.0, "averageTemp": 5.0,
                "averageVisibility": 15.0, "difficulty": "Advanced",
                "curation_score": 8.8, "popularity_score": 7.0, "access_level": "shore",
            },
            "_sites": [
                ("Shiretoko UNESCO Ice Dives", "Shore", "Advanced", ["ice diving", "sea eagles overhead", "cold Arctic water"], ["cold-water", "advanced-challenges"]),
                ("Notoro Lake", "Shore", "Intermediate", ["sea angels", "unique", "cold water"], ["cold-water"]),
                ("Shakotan Peninsula", "Reef", "Intermediate", ["kelp forest", "reef fish", "clear water"], ["cold-water"]),
                ("Cape Kamui", "Shore", "Intermediate", ["reef fish", "macro", "cold water"], ["cold-water", "macro-muck"]),
                ("Rebun Island", "Reef", "Intermediate", ["remote", "cold water", "unique fauna"], ["cold-water"]),
                ("Asamushi", "Shore", "Beginner", ["shore", "macro", "cold water"], ["cold-water", "beginner-friendly"]),
                ("Hakodate Bay", "Shore", "Intermediate", ["shore", "kelp", "fish"], ["cold-water"]),
                ("Akkeshi", "Shore", "Advanced", ["ice diving", "scallops", "cold water"], ["cold-water", "advanced-challenges"]),
            ],
        },
        {
            "id": "hong-kong-guangdong",
            "name": "Hong Kong & South China Sea",
            "country_id": "HK", "country": "Hong Kong",
            "latitude": 22.3, "longitude": 114.2,
            "bounds": {"min_lat": 21.0, "max_lat": 23.5, "min_lon": 113.0, "max_lon": 115.5},
            "tagline": "Surprising reefs on Asia's doorstep",
            "best_season": "September–December",
            "defaults": {
                "averageDepth": 10.0, "maxDepth": 20.0, "averageTemp": 24.0,
                "averageVisibility": 5.0, "difficulty": "Beginner",
                "curation_score": 7.5, "popularity_score": 7.0, "access_level": "boat",
            },
            "_sites": [
                ("Mirs Bay", "Reef", "Beginner", ["coral", "reef fish", "macro"], ["beginner-friendly"]),
                ("Hoi Ha Wan Marine Park", "Reef", "Beginner", ["marine park", "coral", "fish"], ["beginner-friendly"]),
                ("Sharp Island", "Reef", "Beginner", ["shore", "reef fish", "coral"], ["beginner-friendly"]),
                ("Cape D'Aguilar Marine Reserve", "Reef", "Intermediate", ["marine reserve", "reef fish", "macro"], []),
                ("Po Toi Island", "Shore", "Intermediate", ["shore", "unique formations", "reef fish"], []),
                ("Waglan Island", "Reef", "Advanced", ["current", "reef fish", "remote"], ["advanced-challenges"]),
                ("Ninepins Group", "Reef", "Intermediate", ["hexagonal basalt columns", "unique", "reef fish"], []),
            ],
        },
    ],

    "south-africa-south-atlantic": [
        {
            "id": "mozambique-north",
            "name": "Northern Mozambique & Quirimbas",
            "country_id": "MZ", "country": "Mozambique",
            "latitude": -12.0, "longitude": 40.5,
            "bounds": {"min_lat": -15.0, "max_lat": -10.0, "min_lon": 39.5, "max_lon": 41.5},
            "tagline": "Pristine archipelago reefs in northern Mozambique",
            "best_season": "June–October",
            "defaults": {
                "averageDepth": 16.0, "maxDepth": 30.0, "averageTemp": 27.0,
                "averageVisibility": 18.0, "difficulty": "Intermediate",
                "curation_score": 9.0, "popularity_score": 7.0, "access_level": "liveaboard",
            },
            "_sites": [
                ("Quirimbas Archipelago", "Reef", "Intermediate", ["pristine archipelago", "reef fish", "whales"], ["big-animals", "liveaboard"]),
                ("Quilalea Island", "Reef", "Intermediate", ["marine sanctuary", "reef fish", "pristine"], []),
                ("Vamizi Island", "Reef", "Advanced", ["remote", "pristine", "sharks", "mantas"], ["big-animals", "liveaboard", "advanced-challenges"]),
                ("Ilha de Mozambique", "Reef", "Intermediate", ["UNESCO site", "reef", "history"], []),
                ("Ibo Island", "Reef", "Beginner", ["historic island", "reef fish", "calm waters"], ["beginner-friendly"]),
                ("Medjumbe Island", "Reef", "Intermediate", ["remote island resort", "pristine reef", "mantas"], ["big-animals", "liveaboard"]),
            ],
        },
    ],
}
