#!/usr/bin/env python3
"""
Part B of canonical site list — region groups 6-17.
Imported by generate_canonical_list.py.
"""

REGION_GROUPS_B = [

    # =========================================================================
    # 6. RED SEA
    # =========================================================================
    {
        "id": "red-sea",
        "name": "Red Sea",
        "tagline": "Walls, wrecks, and warm desert light",
        "description": "",
        "sort_order": 6,
        "regions": [
            {
                "id": "sharm-el-sheikh",
                "name": "Sharm el-Sheikh & Sinai",
                "country_id": "EG", "country": "Egypt",
                "latitude": 27.9, "longitude": 34.33,
                "bounds": {"min_lat": 27.7, "max_lat": 28.2, "min_lon": 34.0, "max_lon": 34.7},
                "tagline": "Classic Red Sea reef diving",
                "best_season": "March–May, September–November",
                "defaults": {
                    "averageDepth": 18.0, "maxDepth": 40.0, "averageTemp": 26.0,
                    "averageVisibility": 25.0, "difficulty": "Intermediate",
                    "curation_score": 9.0, "popularity_score": 9.2, "access_level": "boat",
                },
                "_sites": [
                    ("Ras Mohammed National Park", "Reef", "Intermediate", ["walls", "schooling fish", "sharks"], ["big-animals"]),
                    ("Shark Reef", "Wall", "Intermediate", ["sharks", "wall", "current"], ["big-animals"]),
                    ("Jolanda Reef", "Reef", "Intermediate", ["reef", "cargo", "turtles"], []),
                    ("Ras Um Sid", "Reef", "Beginner", ["coral pillars", "reef fish"], ["beginner-friendly"]),
                    ("The Tower", "Wall", "Intermediate", ["wall", "soft coral"], []),
                    ("Garden Reef", "Reef", "Beginner", ["coral garden", "fish"], ["beginner-friendly"]),
                    ("Shark Bay", "Shore", "Beginner", ["sharks", "shore", "rays"], ["big-animals", "beginner-friendly"]),
                    ("White Knight", "Reef", "Intermediate", ["coral", "current", "fish"], []),
                    ("Amphoras", "Reef", "Beginner", ["amphoras", "coral", "history"], []),
                    ("Pinky's Wall", "Wall", "Intermediate", ["wall", "soft coral", "macro"], []),
                    ("Temple", "Reef", "Beginner", ["coral garden", "beginners"], ["beginner-friendly"]),
                    ("Middle Garden", "Reef", "Beginner", ["coral", "reef fish"], ["beginner-friendly"]),
                ],
            },
            {
                "id": "hurghada",
                "name": "Hurghada & El Gouna",
                "country_id": "EG", "country": "Egypt",
                "latitude": 27.25, "longitude": 33.85,
                "bounds": {"min_lat": 26.8, "max_lat": 27.6, "min_lon": 33.5, "max_lon": 34.2},
                "tagline": "Accessible reefs and dive training hub",
                "best_season": "Year-round",
                "defaults": {
                    "averageDepth": 15.0, "maxDepth": 35.0, "averageTemp": 25.0,
                    "averageVisibility": 20.0, "difficulty": "Beginner",
                    "curation_score": 8.5, "popularity_score": 8.8, "access_level": "boat",
                },
                "_sites": [
                    ("Abu Nuhas Wrecks", "Wreck", "Intermediate", ["multiple wrecks", "coral growth"], ["wreck-capitals"]),
                    ("Giannis D", "Wreck", "Intermediate", ["famous wreck", "coral"], ["wreck-capitals"]),
                    ("Carnatic", "Wreck", "Intermediate", ["historic wreck", "coral"], ["wreck-capitals"]),
                    ("Sha'ab Abu Nuhas", "Reef", "Intermediate", ["reef", "wrecks nearby"], []),
                    ("Dolphin House", "Reef", "Beginner", ["dolphins", "reef"], ["big-animals", "beginner-friendly"]),
                    ("Gifton Island", "Reef", "Beginner", ["coral garden", "fish"], ["beginner-friendly"]),
                    ("Umm Gamar", "Reef", "Intermediate", ["reef", "current", "fish"], []),
                    ("Abu Hashish", "Reef", "Beginner", ["coral", "reef fish"], ["beginner-friendly"]),
                    ("Careless Reef", "Reef", "Intermediate", ["reef", "fish diversity"], []),
                    ("Sha'ab Sabina", "Reef", "Beginner", ["coral garden", "beginners"], ["beginner-friendly"]),
                ],
            },
            {
                "id": "dahab",
                "name": "Dahab & Gulf of Aqaba",
                "country_id": "EG", "country": "Egypt",
                "latitude": 28.5, "longitude": 34.52,
                "bounds": {"min_lat": 28.3, "max_lat": 29.0, "min_lon": 34.3, "max_lon": 34.8},
                "tagline": "The Blue Hole and world-class shore diving",
                "best_season": "March–May, September–November",
                "defaults": {
                    "averageDepth": 18.0, "maxDepth": 40.0, "averageTemp": 24.0,
                    "averageVisibility": 25.0, "difficulty": "Intermediate",
                    "curation_score": 9.1, "popularity_score": 9.0, "access_level": "shore",
                },
                "_sites": [
                    ("Blue Hole Dahab", "Cave", "Advanced", ["famous sinkhole", "arch", "deep"], ["caves-cenotes", "advanced-challenges"]),
                    ("The Bells", "Wall", "Advanced", ["chimney", "wall", "current"], ["advanced-challenges"]),
                    ("The Canyon", "Cave", "Intermediate", ["canyon", "cavern", "fish"], ["caves-cenotes"]),
                    ("Lighthouse", "Reef", "Beginner", ["shore", "coral", "fish"], ["beginner-friendly"]),
                    ("Islands", "Reef", "Beginner", ["coral pinnacles", "fish"], ["beginner-friendly"]),
                    ("Three Pools", "Reef", "Beginner", ["shore", "macro", "reef fish"], ["beginner-friendly"]),
                    ("Eel Garden Dahab", "Reef", "Beginner", ["garden eels", "sandy", "macro"], ["beginner-friendly"]),
                    ("The Boiler", "Reef", "Intermediate", ["pinnacle", "coral", "fish"], []),
                    ("Golden Blocks", "Wall", "Intermediate", ["wall", "coral", "fish"], []),
                    ("Napoleon Reef", "Reef", "Beginner", ["napoleon fish", "coral"], ["beginner-friendly"]),
                ],
            },
            {
                "id": "red-sea-liveaboard",
                "name": "Red Sea Liveaboard Routes",
                "country_id": "EG", "country": "Egypt",
                "latitude": 25.0, "longitude": 35.5,
                "bounds": {"min_lat": 22.0, "max_lat": 27.5, "min_lon": 34.0, "max_lon": 37.0},
                "tagline": "Remote reefs, hammerheads, and pristine walls",
                "best_season": "June–September for south; year-round for north",
                "defaults": {
                    "averageDepth": 20.0, "maxDepth": 40.0, "averageTemp": 27.0,
                    "averageVisibility": 25.0, "difficulty": "Advanced",
                    "curation_score": 9.4, "popularity_score": 8.5, "access_level": "liveaboard",
                },
                "_sites": [
                    ("Brothers Islands", "Wall", "Advanced", ["hammerheads", "sharks", "pelagic", "wall"], ["big-animals", "liveaboard", "advanced-challenges"]),
                    ("Daedalus Reef", "Reef", "Advanced", ["hammerheads", "thresher sharks", "remote"], ["big-animals", "liveaboard"]),
                    ("Elphinstone Reef", "Wall", "Advanced", ["oceanic whitetips", "wall", "current"], ["big-animals", "liveaboard", "advanced-challenges"]),
                    ("Rocky Island", "Reef", "Advanced", ["remote", "pelagic", "sharks"], ["big-animals", "liveaboard"]),
                    ("Zabargad Island", "Reef", "Advanced", ["remote", "pristine", "sharks"], ["big-animals", "liveaboard"]),
                    ("SS Thistlegorm", "Wreck", "Intermediate", ["famous WWII wreck", "artifacts", "fish"], ["wreck-capitals", "liveaboard"]),
                    ("Sha'ab Rumi", "Reef", "Advanced", ["Jacques Cousteau", "sharks", "walls"], ["big-animals", "liveaboard"]),
                    ("Sanganeb", "Reef", "Advanced", ["remote", "sharks", "walls"], ["big-animals", "liveaboard"]),
                    ("Fury Shoals", "Reef", "Intermediate", ["remote", "pristine", "fish diversity"], ["liveaboard"]),
                    ("St. John's Reef", "Reef", "Advanced", ["remote", "pristine", "sharks"], ["big-animals", "liveaboard"]),
                    ("Sha'ab Sataya", "Reef", "Intermediate", ["dolphins", "remote"], ["big-animals", "liveaboard"]),
                    ("Mersa Alam", "Shore", "Beginner", ["dugong", "shore", "seagrass"], ["big-animals"]),
                ],
            },
        ],
    },

    # =========================================================================
    # 7. MALDIVES & INDIAN OCEAN ATOLLS
    # =========================================================================
    {
        "id": "maldives-indian-ocean",
        "name": "Maldives & Indian Ocean",
        "tagline": "Mantas, whale sharks, and turquoise atolls",
        "description": "",
        "sort_order": 7,
        "regions": [
            {
                "id": "maldives-north-male-atoll",
                "name": "North & South Malé Atoll",
                "country_id": "MV", "country": "Maldives",
                "latitude": 4.2, "longitude": 73.5,
                "bounds": {"min_lat": 3.5, "max_lat": 4.5, "min_lon": 73.0, "max_lon": 74.0},
                "tagline": "Classic channel diving and manta points",
                "best_season": "December–April",
                "defaults": {
                    "averageDepth": 16.0, "maxDepth": 30.0, "averageTemp": 28.0,
                    "averageVisibility": 20.0, "difficulty": "Intermediate",
                    "curation_score": 9.2, "popularity_score": 9.3, "access_level": "boat",
                },
                "_sites": [
                    ("Banana Reef", "Reef", "Intermediate", ["reef", "fish diversity", "current"], []),
                    ("HP Reef", "Reef", "Advanced", ["current", "schooling fish", "sharks"], ["big-animals", "advanced-challenges"]),
                    ("Maaya Thila", "Reef", "Advanced", ["night diving", "white-tip sharks", "current"], ["big-animals", "advanced-challenges"]),
                    ("Lankan Manta Point", "Reef", "Intermediate", ["manta rays", "cleaning station"], ["big-animals"]),
                    ("Fish Head", "Reef", "Intermediate", ["grey reef sharks", "schooling fish"], ["big-animals"]),
                    ("Kuda Thila", "Reef", "Advanced", ["current", "sharks", "pelagic"], ["big-animals", "advanced-challenges"]),
                    ("Nassimo Thila", "Reef", "Intermediate", ["soft coral", "fish diversity"], []),
                    ("Lion's Head", "Reef", "Intermediate", ["reef", "sharks", "fish"], ["big-animals"]),
                    ("Vaadhoo Caves", "Cave", "Intermediate", ["cave", "bioluminescence", "reef fish"], ["caves-cenotes"]),
                    ("Paradise Rock", "Reef", "Beginner", ["coral", "reef fish"], ["beginner-friendly"]),
                ],
            },
            {
                "id": "maldives-ari-atoll",
                "name": "Ari Atoll",
                "country_id": "MV", "country": "Maldives",
                "latitude": 3.9, "longitude": 72.8,
                "bounds": {"min_lat": 3.3, "max_lat": 4.5, "min_lon": 72.4, "max_lon": 73.2},
                "tagline": "Whale shark capital of the Maldives",
                "best_season": "December–April",
                "defaults": {
                    "averageDepth": 18.0, "maxDepth": 35.0, "averageTemp": 28.0,
                    "averageVisibility": 22.0, "difficulty": "Intermediate",
                    "curation_score": 9.4, "popularity_score": 9.2, "access_level": "boat",
                },
                "_sites": [
                    ("Manta Point South Ari", "Reef", "Intermediate", ["manta rays", "cleaning station"], ["big-animals"]),
                    ("Rasdhoo Madivaru", "Reef", "Advanced", ["hammerheads", "dawn dive", "deep"], ["big-animals", "advanced-challenges"]),
                    ("Kudarah Thila", "Reef", "Advanced", ["current", "schooling fish", "sharks"], ["big-animals", "advanced-challenges"]),
                    ("Mahibadhoo Wreck", "Wreck", "Intermediate", ["wreck", "coral growth", "reef fish"], ["wreck-capitals"]),
                    ("Fesdhoo Wreck", "Wreck", "Intermediate", ["wreck", "reef fish"], ["wreck-capitals"]),
                    ("Dhigurah Sandbar", "Shore", "Beginner", ["whale sharks", "snorkel area"], ["big-animals", "beginner-friendly"]),
                    ("Alimatha Jetty", "Shore", "Beginner", ["nurse sharks", "rays", "night diving"], ["big-animals", "beginner-friendly"]),
                    ("Ellaidhoo Housereef", "Shore", "Beginner", ["house reef", "reef fish", "turtles"], ["beginner-friendly"]),
                    ("Moofushi Kandu", "Drift", "Advanced", ["current", "sharks", "pelagic"], ["big-animals", "advanced-challenges"]),
                    ("Thundufushi Thila", "Reef", "Intermediate", ["soft coral", "fish diversity"], []),
                ],
            },
            {
                "id": "maldives-liveaboard",
                "name": "Maldives Liveaboard (Outer Atolls)",
                "country_id": "MV", "country": "Maldives",
                "latitude": 2.0, "longitude": 73.0,
                "bounds": {"min_lat": 0.0, "max_lat": 5.5, "min_lon": 72.0, "max_lon": 74.5},
                "tagline": "Remote atolls, pristine reefs, big pelagics",
                "best_season": "Year-round (varies by atoll)",
                "defaults": {
                    "averageDepth": 20.0, "maxDepth": 40.0, "averageTemp": 28.0,
                    "averageVisibility": 25.0, "difficulty": "Advanced",
                    "curation_score": 9.5, "popularity_score": 8.8, "access_level": "liveaboard",
                },
                "_sites": [
                    ("Addu Atoll", "Reef", "Advanced", ["remote", "pristine", "sharks", "wrecks"], ["big-animals", "liveaboard"]),
                    ("Fuvahmulah", "Reef", "Advanced", ["tiger sharks", "thresher sharks", "deep"], ["big-animals", "liveaboard", "advanced-challenges"]),
                    ("Laamu Atoll", "Reef", "Intermediate", ["remote", "manta rays", "coral"], ["big-animals", "liveaboard"]),
                    ("Huvadhu Atoll", "Reef", "Advanced", ["remote", "sharks", "pelagic"], ["big-animals", "liveaboard"]),
                    ("Baa Atoll", "Reef", "Intermediate", ["UNESCO biosphere", "manta rays", "whale sharks"], ["big-animals", "liveaboard"]),
                    ("Hanifaru Bay", "Reef", "Beginner", ["mass manta feeding", "whale sharks"], ["big-animals"]),
                    ("Thaa Atoll", "Reef", "Advanced", ["remote", "pristine reefs"], ["liveaboard"]),
                ],
            },
            {
                "id": "seychelles",
                "name": "Seychelles",
                "country_id": "SC", "country": "Seychelles",
                "latitude": -4.7, "longitude": 55.5,
                "bounds": {"min_lat": -10.0, "max_lat": -3.8, "min_lon": 55.0, "max_lon": 56.3},
                "tagline": "Granite reefs and whale shark aggregations",
                "best_season": "October–May",
                "defaults": {
                    "averageDepth": 18.0, "maxDepth": 35.0, "averageTemp": 28.0,
                    "averageVisibility": 20.0, "difficulty": "Intermediate",
                    "curation_score": 8.8, "popularity_score": 8.2, "access_level": "boat",
                },
                "_sites": [
                    ("Shark Bank", "Reef", "Advanced", ["sharks", "whale sharks", "pelagic"], ["big-animals", "advanced-challenges"]),
                    ("Ennerdale Wreck", "Wreck", "Intermediate", ["WWII wreck", "coral growth"], ["wreck-capitals"]),
                    ("Ave Maria Rocks", "Reef", "Intermediate", ["granite rocks", "fish diversity"], []),
                    ("Aldabra Atoll", "Reef", "Advanced", ["UNESCO", "remote", "hammerheads", "pristine"], ["big-animals", "liveaboard"]),
                    ("Twin Barges", "Wreck", "Beginner", ["twin wrecks", "reef fish"], ["wreck-capitals", "beginner-friendly"]),
                    ("Brissare Rocks", "Reef", "Intermediate", ["reef fish", "granite", "soft coral"], []),
                    ("White Bank", "Reef", "Advanced", ["whale sharks", "remote", "pelagic"], ["big-animals"]),
                    ("Conception Island", "Reef", "Intermediate", ["reef", "turtles", "sharks"], ["big-animals"]),
                ],
            },
            {
                "id": "mauritius-reunion",
                "name": "Mauritius & Réunion",
                "country_id": "MU", "country": "Mauritius",
                "latitude": -20.3, "longitude": 57.6,
                "bounds": {"min_lat": -21.5, "max_lat": -19.5, "min_lon": 55.5, "max_lon": 58.0},
                "tagline": "Dramatic seamounts and Indian Ocean pelagics",
                "best_season": "October–April",
                "defaults": {
                    "averageDepth": 18.0, "maxDepth": 35.0, "averageTemp": 26.0,
                    "averageVisibility": 20.0, "difficulty": "Intermediate",
                    "curation_score": 8.5, "popularity_score": 7.8, "access_level": "boat",
                },
                "_sites": [
                    ("Shark Pit Mauritius", "Reef", "Advanced", ["sharks", "bull sharks", "current"], ["big-animals", "advanced-challenges"]),
                    ("Stella Maru Wreck", "Wreck", "Intermediate", ["wreck", "coral growth", "reef fish"], ["wreck-capitals"]),
                    ("Holt's Rock", "Reef", "Intermediate", ["reef", "fish diversity", "macro"], []),
                    ("Cathedral", "Cave", "Intermediate", ["cavern", "light rays", "reef fish"], ["caves-cenotes"]),
                    ("La Passe", "Reef", "Beginner", ["coral garden", "reef fish"], ["beginner-friendly"]),
                    ("Blue Bay Marine Park", "Reef", "Beginner", ["protected", "coral", "fish"], ["beginner-friendly"]),
                    ("Passage de l'Est", "Drift", "Advanced", ["current", "sharks", "pelagic"], ["big-animals", "advanced-challenges"]),
                    ("Rivière Noire", "Reef", "Intermediate", ["turtles", "reef", "fish"], []),
                ],
            },
        ],
    },

    # =========================================================================
    # 8. EAST AFRICA & ARABIA
    # =========================================================================
    {
        "id": "east-africa-arabia",
        "name": "East Africa & Arabia",
        "tagline": "Whale sharks, dugongs, and untouched reefs",
        "description": "",
        "sort_order": 8,
        "regions": [
            {
                "id": "mozambique-channel",
                "name": "Mozambique & Tofo",
                "country_id": "MZ", "country": "Mozambique",
                "latitude": -23.8, "longitude": 35.5,
                "bounds": {"min_lat": -26.0, "max_lat": -15.0, "min_lon": 35.0, "max_lon": 37.0},
                "tagline": "Whale sharks and mantas off Africa's east coast",
                "best_season": "October–March",
                "defaults": {
                    "averageDepth": 16.0, "maxDepth": 30.0, "averageTemp": 26.0,
                    "averageVisibility": 12.0, "difficulty": "Intermediate",
                    "curation_score": 9.0, "popularity_score": 7.8, "access_level": "boat",
                },
                "_sites": [
                    ("Manta Reef Tofo", "Reef", "Intermediate", ["manta rays", "whale sharks", "current"], ["big-animals"]),
                    ("Barra Reef", "Reef", "Intermediate", ["reef", "turtles", "fish diversity"], []),
                    ("Rochen Reef", "Reef", "Beginner", ["reef fish", "coral", "turtles"], ["beginner-friendly"]),
                    ("Paindane Reef", "Reef", "Intermediate", ["reef", "whale sharks"], ["big-animals"]),
                    ("Pomene Pinnacles", "Reef", "Intermediate", ["pinnacles", "fish"], []),
                    ("Bazaruto Archipelago", "Reef", "Intermediate", ["dugong", "pristine", "remote"], ["big-animals"]),
                    ("Inhambane Bay", "Reef", "Beginner", ["whale sharks", "mantas", "calm water"], ["big-animals", "beginner-friendly"]),
                ],
            },
            {
                "id": "kenya-zanzibar",
                "name": "Kenya, Tanzania & Zanzibar",
                "country_id": "TZ", "country": "Tanzania",
                "latitude": -6.2, "longitude": 39.7,
                "bounds": {"min_lat": -8.0, "max_lat": -2.5, "min_lon": 39.0, "max_lon": 41.0},
                "tagline": "Pristine East African coral gardens",
                "best_season": "July–September",
                "defaults": {
                    "averageDepth": 14.0, "maxDepth": 28.0, "averageTemp": 27.0,
                    "averageVisibility": 15.0, "difficulty": "Beginner",
                    "curation_score": 8.7, "popularity_score": 7.8, "access_level": "boat",
                },
                "_sites": [
                    ("Mnemba Atoll", "Reef", "Intermediate", ["pristine reef", "dolphins", "fish"], ["big-animals"]),
                    ("Leven Bank", "Reef", "Advanced", ["remote", "sharks", "pelagic"], ["big-animals", "advanced-challenges"]),
                    ("Pemba Channel", "Reef", "Advanced", ["walls", "current", "pelagic"], ["big-animals", "advanced-challenges"]),
                    ("Kinasi Pass", "Drift", "Intermediate", ["channel", "current", "fish"], []),
                    ("Bat Cave Zanzibar", "Cave", "Intermediate", ["cave", "fish", "cavern"], ["caves-cenotes"]),
                    ("Chumbe Island", "Reef", "Beginner", ["protected reef", "coral", "fish"], ["beginner-friendly"]),
                    ("Aliwal Shoal", "Reef", "Advanced", ["ragged tooth sharks", "bull sharks", "current"], ["big-animals", "advanced-challenges"]),
                    ("Protea Banks", "Reef", "Advanced", ["bull sharks", "hammerheads", "ragged tooth"], ["big-animals", "advanced-challenges"]),
                    ("Watamu Marine Park", "Reef", "Beginner", ["protected reef", "turtles", "fish"], ["beginner-friendly"]),
                    ("Wasini Island", "Reef", "Beginner", ["reef fish", "coral", "dolphins"], ["beginner-friendly"]),
                ],
            },
            {
                "id": "oman-uae",
                "name": "Oman & UAE",
                "country_id": "OM", "country": "Oman",
                "latitude": 22.0, "longitude": 59.0,
                "bounds": {"min_lat": 16.0, "max_lat": 26.0, "min_lon": 51.0, "max_lon": 61.0},
                "tagline": "Arabia's hidden dive gems",
                "best_season": "October–May",
                "defaults": {
                    "averageDepth": 15.0, "maxDepth": 30.0, "averageTemp": 28.0,
                    "averageVisibility": 12.0, "difficulty": "Intermediate",
                    "curation_score": 8.0, "popularity_score": 6.5, "access_level": "boat",
                },
                "_sites": [
                    ("Daymaniyat Islands", "Reef", "Intermediate", ["reef", "turtles", "fish"], []),
                    ("Bandar Khayran", "Reef", "Beginner", ["coral", "reef fish", "calm"], ["beginner-friendly"]),
                    ("Hallaniyat Islands", "Reef", "Advanced", ["remote", "whale sharks", "pelagic"], ["big-animals", "liveaboard"]),
                    ("Muscat Barge", "Wreck", "Beginner", ["wreck", "reef fish"], ["wreck-capitals", "beginner-friendly"]),
                    ("Dibba Rock", "Reef", "Intermediate", ["pinnacle", "fish diversity"], []),
                    ("Snoopy Island", "Reef", "Beginner", ["shore", "reef fish", "macro"], ["beginner-friendly"]),
                    ("Martini Rock", "Reef", "Advanced", ["current", "sharks", "pelagic"], ["big-animals", "advanced-challenges"]),
                    ("Lima Rock", "Wall", "Advanced", ["wall", "barracuda", "current"], ["advanced-challenges"]),
                ],
            },
        ],
    },

    # =========================================================================
    # 9. AUSTRALIA & NEW ZEALAND
    # =========================================================================
    {
        "id": "australia-new-zealand",
        "name": "Australia & New Zealand",
        "tagline": "Great Barrier Reef to kelp forests",
        "description": "",
        "sort_order": 9,
        "regions": [
            {
                "id": "great-barrier-reef",
                "name": "Great Barrier Reef",
                "country_id": "AU", "country": "Australia",
                "latitude": -18.0, "longitude": 147.5,
                "bounds": {"min_lat": -24.5, "max_lat": -10.5, "min_lon": 144.0, "max_lon": 154.0},
                "tagline": "World's largest coral reef system",
                "best_season": "June–October",
                "defaults": {
                    "averageDepth": 16.0, "maxDepth": 30.0, "averageTemp": 26.0,
                    "averageVisibility": 20.0, "difficulty": "Beginner",
                    "curation_score": 9.3, "popularity_score": 9.5, "access_level": "boat",
                },
                "_sites": [
                    ("Cod Hole", "Reef", "Intermediate", ["potato cod", "hand feeding", "fish"], ["big-animals"]),
                    ("Osprey Reef", "Reef", "Advanced", ["hammerheads", "sharks", "remote", "walls"], ["big-animals", "liveaboard", "advanced-challenges"]),
                    ("Ribbon Reefs", "Reef", "Intermediate", ["pristine coral", "fish diversity"], ["liveaboard"]),
                    ("Coral Sea", "Wall", "Advanced", ["remote", "pristine walls", "pelagic"], ["big-animals", "liveaboard"]),
                    ("Bougainville Reef", "Reef", "Advanced", ["remote", "sharks", "pristine"], ["big-animals", "liveaboard"]),
                    ("Hastings Reef", "Reef", "Beginner", ["coral garden", "reef fish"], ["beginner-friendly"]),
                    ("Norman Reef", "Reef", "Beginner", ["coral", "turtles", "reef fish"], ["beginner-friendly"]),
                    ("Michaelmas Cay", "Reef", "Beginner", ["seabirds", "coral", "turtles"], ["beginner-friendly"]),
                    ("Agincourt Reefs", "Reef", "Intermediate", ["outer reef", "coral", "pelagic"], []),
                    ("Steve's Bommie", "Reef", "Intermediate", ["macro", "soft coral", "fish"], ["macro-muck"]),
                    ("Lighthouse Bommies", "Reef", "Intermediate", ["coral bommies", "fish"], []),
                    ("Flinders Reef", "Reef", "Advanced", ["remote", "sharks", "walls"], ["big-animals", "liveaboard"]),
                ],
            },
            {
                "id": "coral-sea-outer",
                "name": "Coral Sea & Outer Reefs (Liveaboard)",
                "country_id": "AU", "country": "Australia",
                "latitude": -16.0, "longitude": 150.0,
                "bounds": {"min_lat": -22.0, "max_lat": -10.0, "min_lon": 147.0, "max_lon": 157.0},
                "tagline": "Remote open ocean reefs with big animal encounters",
                "best_season": "July–November",
                "defaults": {
                    "averageDepth": 20.0, "maxDepth": 40.0, "averageTemp": 25.0,
                    "averageVisibility": 30.0, "difficulty": "Advanced",
                    "curation_score": 9.5, "popularity_score": 8.0, "access_level": "liveaboard",
                },
                "_sites": [
                    ("North Horn Osprey", "Reef", "Advanced", ["shark feeding", "wall", "pelagic"], ["big-animals", "liveaboard"]),
                    ("Blue Wall Osprey", "Wall", "Advanced", ["sheer wall", "pelagic", "sharks"], ["big-animals", "liveaboard"]),
                    ("Admiralty Anchor", "Reef", "Advanced", ["remote", "pristine", "sharks"], ["big-animals", "liveaboard"]),
                    ("Boot Reef", "Reef", "Advanced", ["remote", "pristine", "fish diversity"], ["liveaboard"]),
                    ("Wreck of the Yongala", "Wreck", "Intermediate", ["epic wreck", "bull sharks", "manta rays", "schooling fish"], ["wreck-capitals", "big-animals"]),
                ],
            },
            {
                "id": "western-australia",
                "name": "Western Australia & Ningaloo",
                "country_id": "AU", "country": "Australia",
                "latitude": -22.5, "longitude": 113.7,
                "bounds": {"min_lat": -28.0, "max_lat": -21.0, "min_lon": 112.0, "max_lon": 115.0},
                "tagline": "Whale sharks and pristine remote reefs",
                "best_season": "March–July (whale sharks)",
                "defaults": {
                    "averageDepth": 14.0, "maxDepth": 28.0, "averageTemp": 24.0,
                    "averageVisibility": 15.0, "difficulty": "Beginner",
                    "curation_score": 9.0, "popularity_score": 8.2, "access_level": "boat",
                },
                "_sites": [
                    ("Ningaloo Reef", "Reef", "Beginner", ["whale sharks", "snorkel", "coral"], ["big-animals", "beginner-friendly"]),
                    ("Navy Pier", "Shore", "Intermediate", ["jetty", "macro", "fish diversity", "wobbegongs"], ["macro-muck"]),
                    ("Muiron Islands", "Reef", "Intermediate", ["reef", "mantas", "fish"], ["big-animals"]),
                    ("Coral Bay", "Reef", "Beginner", ["coral", "manta rays", "reef fish"], ["big-animals", "beginner-friendly"]),
                    ("Rottnest Island", "Reef", "Beginner", ["seals", "reef fish", "coral"], ["big-animals", "beginner-friendly"]),
                    ("Rowley Shoals", "Reef", "Advanced", ["remote", "pristine", "pelagic"], ["big-animals", "liveaboard"]),
                    ("Scott Reef", "Reef", "Advanced", ["remote", "sharks", "walls"], ["big-animals", "liveaboard"]),
                ],
            },
            {
                "id": "new-zealand",
                "name": "New Zealand",
                "country_id": "NZ", "country": "New Zealand",
                "latitude": -36.9, "longitude": 174.8,
                "bounds": {"min_lat": -46.5, "max_lat": -34.0, "min_lon": 166.0, "max_lon": 178.5},
                "tagline": "Kelp forests, Poor Knights, and WWII wrecks",
                "best_season": "December–April",
                "defaults": {
                    "averageDepth": 15.0, "maxDepth": 30.0, "averageTemp": 18.0,
                    "averageVisibility": 15.0, "difficulty": "Intermediate",
                    "curation_score": 8.8, "popularity_score": 7.8, "access_level": "boat",
                },
                "_sites": [
                    ("Poor Knights Islands", "Wall", "Intermediate", ["arches", "walls", "fish", "kelp"], ["cold-water"]),
                    ("Rainbow Warrior Wreck", "Wreck", "Intermediate", ["famous wreck", "coral growth", "reef fish"], ["wreck-capitals"]),
                    ("Mikhail Lermontov", "Wreck", "Advanced", ["large wreck", "deep", "fish"], ["wreck-capitals", "advanced-challenges"]),
                    ("Mokohinau Islands", "Reef", "Intermediate", ["reef", "fish diversity", "remote"], []),
                    ("Goat Island", "Shore", "Beginner", ["marine reserve", "snapper", "shore diving"], ["beginner-friendly", "cold-water"]),
                    ("White Island", "Reef", "Advanced", ["volcanic", "unique", "warm geothermal"], ["advanced-challenges"]),
                    ("Leigh Cave", "Cave", "Intermediate", ["cavern", "fish", "invertebrates"], ["caves-cenotes", "cold-water"]),
                    ("Tuhua (Mayor Island)", "Reef", "Intermediate", ["reef", "fish diversity"], []),
                ],
            },
        ],
    },

    # =========================================================================
    # 10. PACIFIC ISLANDS
    # =========================================================================
    {
        "id": "pacific-islands",
        "name": "Pacific Islands",
        "tagline": "Remote paradise reefs and big ocean encounters",
        "description": "",
        "sort_order": 10,
        "regions": [
            {
                "id": "fiji",
                "name": "Fiji",
                "country_id": "FJ", "country": "Fiji",
                "latitude": -17.7, "longitude": 177.4,
                "bounds": {"min_lat": -20.0, "max_lat": -15.0, "min_lon": 177.0, "max_lon": 180.0},
                "tagline": "Soft coral capital of the world",
                "best_season": "April–October",
                "defaults": {
                    "averageDepth": 16.0, "maxDepth": 30.0, "averageTemp": 27.0,
                    "averageVisibility": 22.0, "difficulty": "Intermediate",
                    "curation_score": 9.3, "popularity_score": 9.0, "access_level": "boat",
                },
                "_sites": [
                    ("Great White Wall", "Wall", "Intermediate", ["soft coral", "white coral", "wall"], []),
                    ("Rainbow Reef", "Reef", "Intermediate", ["soft coral", "fish diversity", "colorful"], []),
                    ("Shark Alley Fiji", "Reef", "Advanced", ["bull sharks", "shark feeding", "current"], ["big-animals", "advanced-challenges"]),
                    ("Beqa Lagoon", "Reef", "Intermediate", ["bull sharks", "tiger sharks", "shark feeding"], ["big-animals"]),
                    ("Astrolabe Reef", "Reef", "Advanced", ["remote", "walls", "pelagic"], ["liveaboard", "advanced-challenges"]),
                    ("Purple Wall", "Wall", "Intermediate", ["purple soft coral", "wall"], []),
                    ("Annie's Bommie", "Reef", "Intermediate", ["soft coral", "macro", "fish"], ["macro-muck"]),
                    ("Ledge", "Wall", "Advanced", ["wall", "current", "pelagic"], ["advanced-challenges"]),
                    ("Coral Gardens Fiji", "Reef", "Beginner", ["coral garden", "reef fish", "snorkel"], ["beginner-friendly"]),
                    ("W Reef", "Reef", "Advanced", ["current", "pelagic", "sharks"], ["big-animals", "advanced-challenges"]),
                    ("Nigali Passage", "Drift", "Advanced", ["current", "grey reef sharks", "fish"], ["big-animals", "advanced-challenges"]),
                    ("Vatu-i-Ra Channel", "Drift", "Advanced", ["current", "sharks", "fish"], ["big-animals", "advanced-challenges"]),
                ],
            },
            {
                "id": "solomon-islands",
                "name": "Solomon Islands",
                "country_id": "SB", "country": "Solomon Islands",
                "latitude": -9.0, "longitude": 160.0,
                "bounds": {"min_lat": -12.0, "max_lat": -6.0, "min_lon": 155.0, "max_lon": 167.0},
                "tagline": "WWII wrecks and untouched reefs",
                "best_season": "April–November",
                "defaults": {
                    "averageDepth": 18.0, "maxDepth": 35.0, "averageTemp": 28.0,
                    "averageVisibility": 20.0, "difficulty": "Intermediate",
                    "curation_score": 9.1, "popularity_score": 7.5, "access_level": "boat",
                },
                "_sites": [
                    ("Iron Bottom Sound", "Wreck", "Intermediate", ["WWII wrecks", "multiple sites", "history"], ["wreck-capitals", "liveaboard"]),
                    ("Bonegi I & II", "Wreck", "Intermediate", ["WWII Japanese wrecks", "coral growth"], ["wreck-capitals"]),
                    ("Mbambanga Island", "Reef", "Advanced", ["pristine reef", "sharks", "remote"], ["big-animals", "liveaboard"]),
                    ("Mary Island", "Wall", "Intermediate", ["wall", "soft coral", "fish"], []),
                    ("Roderick Bay Wrecks", "Wreck", "Advanced", ["multiple wrecks", "deep", "remote"], ["wreck-capitals", "liveaboard"]),
                    ("Munda Lagoon", "Reef", "Beginner", ["lagoon", "coral garden", "reef fish"], ["beginner-friendly"]),
                    ("Kavachi Volcano", "Reef", "Advanced", ["volcanic", "unique", "remote"], ["advanced-challenges"]),
                ],
            },
            {
                "id": "french-polynesia",
                "name": "French Polynesia (Tahiti & Fakarava)",
                "country_id": "PF", "country": "French Polynesia",
                "latitude": -16.5, "longitude": -151.0,
                "bounds": {"min_lat": -23.0, "max_lat": -10.0, "min_lon": -155.0, "max_lon": -145.0},
                "tagline": "Shark walls and UNESCO atolls",
                "best_season": "June–October",
                "defaults": {
                    "averageDepth": 18.0, "maxDepth": 35.0, "averageTemp": 27.0,
                    "averageVisibility": 25.0, "difficulty": "Intermediate",
                    "curation_score": 9.3, "popularity_score": 8.8, "access_level": "boat",
                },
                "_sites": [
                    ("Fakarava South Pass", "Drift", "Advanced", ["grey reef sharks", "wall of sharks", "strong current"], ["big-animals", "advanced-challenges"]),
                    ("Fakarava North Pass", "Drift", "Intermediate", ["sharks", "current", "fish"], ["big-animals"]),
                    ("Tiputa Pass Rangiroa", "Drift", "Advanced", ["dolphins", "sharks", "current"], ["big-animals", "advanced-challenges"]),
                    ("Avatoru Pass Rangiroa", "Drift", "Intermediate", ["current", "reef fish", "sharks"], ["big-animals"]),
                    ("Motu Nui Rangiroa", "Reef", "Intermediate", ["reef fish", "coral"], []),
                    ("Blue Lagoon Rangiroa", "Reef", "Beginner", ["lagoon", "reef fish", "snorkel"], ["beginner-friendly"]),
                    ("Aquarium Moorea", "Reef", "Beginner", ["coral garden", "tropical fish"], ["beginner-friendly"]),
                    ("Tiki Point Moorea", "Reef", "Intermediate", ["lemon sharks", "rays", "fish"], ["big-animals"]),
                    ("Pass Taravao Tahiti", "Drift", "Advanced", ["current", "sharks"], ["big-animals", "advanced-challenges"]),
                    ("Shark Cave Bora Bora", "Cave", "Beginner", ["lemon sharks", "nurse sharks", "cave"], ["big-animals", "caves-cenotes"]),
                    ("Tupai Atoll", "Reef", "Advanced", ["remote", "pristine", "heart-shaped atoll"], ["liveaboard"]),
                ],
            },
            {
                "id": "hawaii",
                "name": "Hawaii",
                "country_id": "US", "country": "United States",
                "latitude": 20.5, "longitude": -157.0,
                "bounds": {"min_lat": 18.5, "max_lat": 22.3, "min_lon": -160.5, "max_lon": -154.5},
                "tagline": "Lava tubes, manta rays, and endemic species",
                "best_season": "April–October",
                "defaults": {
                    "averageDepth": 15.0, "maxDepth": 30.0, "averageTemp": 26.0,
                    "averageVisibility": 25.0, "difficulty": "Beginner",
                    "curation_score": 9.0, "popularity_score": 9.0, "access_level": "boat",
                },
                "_sites": [
                    ("Manta Ray Night Dive Kona", "Shore", "Beginner", ["manta rays", "night diving", "plankton"], ["big-animals", "beginner-friendly"]),
                    ("Garden Eel Cove", "Shore", "Beginner", ["garden eels", "manta rays", "night"], ["big-animals", "beginner-friendly"]),
                    ("Kealakekua Bay", "Reef", "Beginner", ["spinner dolphins", "coral", "reef fish"], ["big-animals", "beginner-friendly"]),
                    ("Old Airport Beach", "Shore", "Beginner", ["turtles", "coral", "reef fish"], ["beginner-friendly"]),
                    ("Cathedrals Lanai", "Cave", "Intermediate", ["lava tubes", "cavern", "light rays", "reef fish"], ["caves-cenotes"]),
                    ("First Cathedral", "Cave", "Intermediate", ["lava tube", "cavern", "fish"], ["caves-cenotes"]),
                    ("Molokini Crater", "Reef", "Beginner", ["clear water", "reef fish", "turtles"], ["beginner-friendly"]),
                    ("Turtle Town", "Reef", "Beginner", ["turtles", "coral", "reef fish"], ["beginner-friendly"]),
                    ("Shark Cove Oahu", "Shore", "Beginner", ["lava rock", "marine life", "macro"], ["beginner-friendly"]),
                    ("Hanauma Bay", "Shore", "Beginner", ["protected bay", "reef fish", "snorkel"], ["beginner-friendly"]),
                    ("Corsair Wreck Oahu", "Wreck", "Intermediate", ["WWII plane", "reef fish"], ["wreck-capitals"]),
                    ("Mahi Wreck Oahu", "Wreck", "Intermediate", ["wreck", "reef fish", "dolphins"], ["wreck-capitals", "big-animals"]),
                ],
            },
            {
                "id": "papua-new-guinea",
                "name": "Papua New Guinea",
                "country_id": "PG", "country": "Papua New Guinea",
                "latitude": -6.3, "longitude": 147.1,
                "bounds": {"min_lat": -12.0, "max_lat": 0.0, "min_lon": 140.0, "max_lon": 157.0},
                "tagline": "WWII wrecks and untouched coral reefs",
                "best_season": "April–November",
                "defaults": {
                    "averageDepth": 18.0, "maxDepth": 35.0, "averageTemp": 28.0,
                    "averageVisibility": 20.0, "difficulty": "Intermediate",
                    "curation_score": 9.2, "popularity_score": 7.8, "access_level": "boat",
                },
                "_sites": [
                    ("SS Macdhui Wreck", "Wreck", "Intermediate", ["WWII wreck", "coral growth", "reef fish"], ["wreck-capitals"]),
                    ("B-17 Flying Fortress", "Wreck", "Intermediate", ["WWII plane wreck", "history"], ["wreck-capitals"]),
                    ("Japanese Zero Wreck", "Wreck", "Intermediate", ["WWII plane", "history"], ["wreck-capitals"]),
                    ("Vanessa's Wall", "Wall", "Intermediate", ["wall", "soft coral", "fish"], []),
                    ("Planet Rock", "Reef", "Advanced", ["current", "sharks", "schooling fish"], ["big-animals", "advanced-challenges"]),
                    ("Magic Passage", "Drift", "Intermediate", ["current", "fish diversity"], []),
                    ("Kimbe Bay", "Reef", "Intermediate", ["biodiversity", "macro", "soft coral"], ["macro-muck"]),
                    ("Fathers Reefs", "Reef", "Intermediate", ["coral", "fish diversity"], []),
                    ("Milne Bay", "Shore", "Beginner", ["muck", "macro", "rare critters"], ["macro-muck"]),
                    ("Tufi", "Wall", "Intermediate", ["walls", "fjords", "fish diversity"], []),
                ],
            },
        ],
    },

    # =========================================================================
    # 11. CARIBBEAN & ATLANTIC
    # =========================================================================
    {
        "id": "caribbean-atlantic",
        "name": "Caribbean & Atlantic",
        "tagline": "Wrecks, walls, and warm tropical reefs",
        "description": "",
        "sort_order": 11,
        "regions": [
            {
                "id": "cayman-islands",
                "name": "Cayman Islands",
                "country_id": "KY", "country": "Cayman Islands",
                "latitude": 19.3, "longitude": -81.4,
                "bounds": {"min_lat": 19.0, "max_lat": 20.0, "min_lon": -82.0, "max_lon": -79.5},
                "tagline": "Walls, stingray city, and classic Caribbean",
                "best_season": "Year-round",
                "defaults": {
                    "averageDepth": 16.0, "maxDepth": 35.0, "averageTemp": 28.0,
                    "averageVisibility": 25.0, "difficulty": "Beginner",
                    "curation_score": 9.1, "popularity_score": 9.2, "access_level": "boat",
                },
                "_sites": [
                    ("Stingray City", "Reef", "Beginner", ["stingrays", "shallow", "snorkel friendly"], ["big-animals", "beginner-friendly"]),
                    ("Kittiwake Wreck", "Wreck", "Beginner", ["sunken ship", "reef fish", "artificial reef"], ["wreck-capitals", "beginner-friendly"]),
                    ("Bloody Bay Wall", "Wall", "Intermediate", ["sheer wall", "deep drop-off", "fish"], []),
                    ("Eden Rock", "Wall", "Beginner", ["tarpon", "turtles", "wall"], ["beginner-friendly"]),
                    ("Devil's Grotto", "Cave", "Intermediate", ["cavern", "tarpon", "reef fish"], ["caves-cenotes"]),
                    ("The Aquarium", "Reef", "Beginner", ["tame fish", "coral", "turtles"], ["beginner-friendly"]),
                    ("USS Kittiwake", "Wreck", "Beginner", ["sunken ship", "reef fish"], ["wreck-capitals", "beginner-friendly"]),
                    ("Big Tunnels", "Cave", "Intermediate", ["tunnel", "swimthrough", "reef fish"], ["caves-cenotes"]),
                    ("Babylon Wall", "Wall", "Intermediate", ["deep wall", "sponges", "fish"], []),
                    ("North Wall Grand Cayman", "Wall", "Intermediate", ["sponges", "coral", "fish"], []),
                ],
            },
            {
                "id": "belize",
                "name": "Belize",
                "country_id": "BZ", "country": "Belize",
                "latitude": 17.1, "longitude": -87.8,
                "bounds": {"min_lat": 15.5, "max_lat": 18.5, "min_lon": -88.5, "max_lon": -87.0},
                "tagline": "Blue Hole and barrier reef",
                "best_season": "March–May, October–November",
                "defaults": {
                    "averageDepth": 15.0, "maxDepth": 35.0, "averageTemp": 27.0,
                    "averageVisibility": 22.0, "difficulty": "Intermediate",
                    "curation_score": 9.0, "popularity_score": 8.8, "access_level": "boat",
                },
                "_sites": [
                    ("Great Blue Hole", "Cave", "Intermediate", ["famous sinkhole", "stalactites", "reef sharks"], ["caves-cenotes", "big-animals"]),
                    ("Half Moon Caye Wall", "Wall", "Intermediate", ["wall", "red-footed boobies", "reef sharks"], ["big-animals"]),
                    ("Lighthouse Reef", "Reef", "Intermediate", ["pristine reef", "reef sharks", "fish"], ["big-animals"]),
                    ("Turneffe Atoll", "Reef", "Intermediate", ["atoll", "reef", "fish diversity", "manatees"], ["big-animals"]),
                    ("Glover's Reef", "Reef", "Intermediate", ["pristine atoll", "reef fish", "remote"], ["liveaboard"]),
                    ("The Elbow", "Drift", "Advanced", ["current", "schooling fish", "sharks"], ["big-animals", "advanced-challenges"]),
                    ("Shark Ray Alley", "Reef", "Beginner", ["nurse sharks", "rays", "shallow"], ["big-animals", "beginner-friendly"]),
                    ("Mexico Rocks", "Reef", "Beginner", ["coral", "fish", "snorkel"], ["beginner-friendly"]),
                    ("Cathedral Belize", "Cave", "Intermediate", ["cavern", "reef fish", "light rays"], ["caves-cenotes"]),
                ],
            },
            {
                "id": "honduras-bay-islands",
                "name": "Honduras Bay Islands",
                "country_id": "HN", "country": "Honduras",
                "latitude": 16.3, "longitude": -86.5,
                "bounds": {"min_lat": 15.8, "max_lat": 16.6, "min_lon": -87.5, "max_lon": -85.8},
                "tagline": "Whale sharks and affordable Caribbean diving",
                "best_season": "March–September",
                "defaults": {
                    "averageDepth": 14.0, "maxDepth": 28.0, "averageTemp": 28.0,
                    "averageVisibility": 22.0, "difficulty": "Beginner",
                    "curation_score": 8.8, "popularity_score": 8.5, "access_level": "boat",
                },
                "_sites": [
                    ("Cayos Cochinos", "Reef", "Intermediate", ["pristine reef", "whale sharks", "remote"], ["big-animals"]),
                    ("Half Moon Bay Wall", "Wall", "Intermediate", ["wall", "coral", "fish"], []),
                    ("Mary's Place", "Cave", "Intermediate", ["fissure", "swimthrough", "fish"], ["caves-cenotes"]),
                    ("Hole in the Wall", "Cave", "Intermediate", ["cavern", "swimthrough"], ["caves-cenotes"]),
                    ("Spooky Channel", "Cave", "Intermediate", ["channel", "swimthrough", "fish"], ["caves-cenotes"]),
                    ("CoCo View Wall", "Wall", "Intermediate", ["wall", "coral", "sponges"], []),
                    ("Herbie's Place", "Reef", "Beginner", ["coral", "reef fish"], ["beginner-friendly"]),
                    ("El Aguila Wreck", "Wreck", "Intermediate", ["wreck", "coral growth", "reef fish"], ["wreck-capitals"]),
                    ("Bite Reef", "Reef", "Beginner", ["reef", "reef fish", "coral"], ["beginner-friendly"]),
                ],
            },
            {
                "id": "cuba-mexico-caribbean",
                "name": "Cuba & Mexican Caribbean",
                "country_id": "MX", "country": "Mexico",
                "latitude": 20.5, "longitude": -87.0,
                "bounds": {"min_lat": 19.5, "max_lat": 23.5, "min_lon": -88.0, "max_lon": -77.0},
                "tagline": "Cenotes, walls, and vibrant Caribbean reefs",
                "best_season": "Year-round",
                "defaults": {
                    "averageDepth": 14.0, "maxDepth": 30.0, "averageTemp": 27.0,
                    "averageVisibility": 25.0, "difficulty": "Beginner",
                    "curation_score": 9.0, "popularity_score": 9.0, "access_level": "boat",
                },
                "_sites": [
                    ("Palancar Reef Cozumel", "Reef", "Intermediate", ["stunning coral", "drift", "wall"], []),
                    ("Santa Rosa Wall Cozumel", "Wall", "Intermediate", ["deep wall", "sponges", "drift"], []),
                    ("Columbia Deep Cozumel", "Wall", "Advanced", ["very deep", "wall", "drift current"], ["advanced-challenges"]),
                    ("Punta Sur Cozumel", "Cave", "Advanced", ["cave system", "moray eels", "current"], ["caves-cenotes", "advanced-challenges"]),
                    ("El Paso del Cedral", "Reef", "Beginner", ["turtles", "reef fish", "coral"], ["beginner-friendly"]),
                    ("Cenote Dos Ojos", "Cave", "Intermediate", ["cavern system", "crystal clear", "stalactites"], ["caves-cenotes"]),
                    ("Gran Cenote", "Cave", "Beginner", ["open cavern", "clear water", "snorkel friendly"], ["caves-cenotes", "beginner-friendly"]),
                    ("Cenote Tajma Ha", "Cave", "Advanced", ["cave diving", "stalactites", "halocline"], ["caves-cenotes", "advanced-challenges"]),
                    ("Cenote Eden", "Cave", "Beginner", ["open cavern", "clear", "fish"], ["caves-cenotes", "beginner-friendly"]),
                    ("MUSA Underwater Museum", "Reef", "Beginner", ["sculptures", "artificial reef", "unique"], ["beginner-friendly"]),
                    ("Manchones Reef", "Reef", "Beginner", ["coral", "turtles", "fish"], ["beginner-friendly"]),
                    ("Jardines de la Reina Cuba", "Reef", "Advanced", ["pristine", "sharks", "crocodiles", "remote"], ["big-animals", "liveaboard", "advanced-challenges"]),
                ],
            },
            {
                "id": "bahamas",
                "name": "Bahamas",
                "country_id": "BS", "country": "Bahamas",
                "latitude": 25.0, "longitude": -77.5,
                "bounds": {"min_lat": 22.0, "max_lat": 27.0, "min_lon": -79.5, "max_lon": -72.5},
                "tagline": "Tiger sharks, reef sharks, and crystal blue holes",
                "best_season": "June–August",
                "defaults": {
                    "averageDepth": 14.0, "maxDepth": 30.0, "averageTemp": 27.0,
                    "averageVisibility": 28.0, "difficulty": "Intermediate",
                    "curation_score": 9.1, "popularity_score": 8.8, "access_level": "boat",
                },
                "_sites": [
                    ("Tiger Beach", "Reef", "Advanced", ["tiger sharks", "lemon sharks", "shallow"], ["big-animals", "advanced-challenges"]),
                    ("Shark Arena Nassau", "Reef", "Intermediate", ["reef sharks", "caribbean reef sharks"], ["big-animals"]),
                    ("Dean's Blue Hole", "Cave", "Advanced", ["deep blue hole", "freediving", "world record"], ["caves-cenotes", "advanced-challenges"]),
                    ("AUTEC Buoys", "Reef", "Advanced", ["oceanic whitetip sharks", "remote"], ["big-animals", "advanced-challenges"]),
                    ("Thunderball Grotto", "Cave", "Beginner", ["snorkel cave", "reef fish", "film location"], ["caves-cenotes", "beginner-friendly"]),
                    ("Sea Hunt Wreck", "Wreck", "Intermediate", ["wreck", "reef fish"], ["wreck-capitals"]),
                    ("Current Cut", "Drift", "Advanced", ["extreme current", "sharks", "fish"], ["big-animals", "advanced-challenges"]),
                    ("Conception Island Wall", "Wall", "Intermediate", ["pristine wall", "remote", "reef fish"], []),
                ],
            },
            {
                "id": "turks-caicos-dominican",
                "name": "Turks & Caicos, Dominican Republic & Puerto Rico",
                "country_id": "TC", "country": "Turks and Caicos",
                "latitude": 21.8, "longitude": -71.9,
                "bounds": {"min_lat": 19.5, "max_lat": 23.0, "min_lon": -73.0, "max_lon": -68.0},
                "tagline": "Pristine walls and humpback whale encounters",
                "best_season": "November–April",
                "defaults": {
                    "averageDepth": 18.0, "maxDepth": 40.0, "averageTemp": 27.0,
                    "averageVisibility": 28.0, "difficulty": "Intermediate",
                    "curation_score": 9.0, "popularity_score": 8.5, "access_level": "boat",
                },
                "_sites": [
                    ("Grace Bay Wall", "Wall", "Intermediate", ["pristine wall", "sponges", "fish"], []),
                    ("The Cathedral TCI", "Cave", "Intermediate", ["cavern", "light rays", "reef fish"], ["caves-cenotes"]),
                    ("West Caicos", "Wall", "Advanced", ["remote", "wall", "hammerheads", "reef sharks"], ["big-animals", "advanced-challenges"]),
                    ("French Cay", "Reef", "Intermediate", ["reef sharks", "fish diversity", "remote"], ["big-animals"]),
                    ("Silver Bank", "Reef", "Intermediate", ["humpback whales", "snorkel", "remote"], ["big-animals", "liveaboard"]),
                    ("La Caleta Wreck", "Wreck", "Beginner", ["shallow wreck", "coral growth", "reef fish"], ["wreck-capitals", "beginner-friendly"]),
                    ("Mona Island", "Reef", "Advanced", ["remote", "pristine", "sharks"], ["big-animals", "liveaboard"]),
                ],
            },
            {
                "id": "bonaire",
                "name": "Bonaire",
                "country_id": "BQ", "country": "Bonaire",
                "latitude": 12.2, "longitude": -68.3,
                "bounds": {"min_lat": 12.0, "max_lat": 12.5, "min_lon": -68.5, "max_lon": -68.0},
                "tagline": "Shore diving paradise, buoyed reef system",
                "best_season": "Year-round",
                "defaults": {
                    "averageDepth": 14.0, "maxDepth": 28.0, "averageTemp": 27.0,
                    "averageVisibility": 25.0, "difficulty": "Beginner",
                    "curation_score": 9.2, "popularity_score": 9.0, "access_level": "shore",
                },
                "_sites": [
                    ("Salt Pier", "Shore", "Beginner", ["pillar coral", "schooling fish", "shore"], ["beginner-friendly"]),
                    ("Hilma Hooker Wreck", "Wreck", "Intermediate", ["famous wreck", "coral growth", "reef fish"], ["wreck-capitals"]),
                    ("Karpata", "Wall", "Beginner", ["wall", "coral", "shore entry"], ["beginner-friendly"]),
                    ("Klein Bonaire", "Reef", "Beginner", ["pristine reef", "turtles", "fish"], ["beginner-friendly"]),
                    ("Town Pier", "Shore", "Intermediate", ["colorful sponges", "night diving", "pier"], ["macro-muck"]),
                    ("Thousand Steps", "Wall", "Intermediate", ["wall", "coral", "fish"], []),
                    ("Something Special", "Shore", "Beginner", ["garden eels", "shore", "macro"], ["beginner-friendly"]),
                    ("Oil Slick Leap", "Wall", "Intermediate", ["wall", "coral", "fish"], []),
                    ("Rappel", "Wall", "Intermediate", ["cliff entry", "wall", "coral"], []),
                    ("Forest", "Reef", "Beginner", ["pillar coral", "elkhorn coral", "fish"], ["beginner-friendly"]),
                ],
            },
        ],
    },

    # =========================================================================
    # 12. MEDITERRANEAN & ATLANTIC EUROPE
    # =========================================================================
    {
        "id": "mediterranean-europe",
        "name": "Mediterranean & Atlantic Europe",
        "tagline": "Posidonia meadows, wrecks, and ancient history",
        "description": "",
        "sort_order": 12,
        "regions": [
            {
                "id": "malta-gozo",
                "name": "Malta & Gozo",
                "country_id": "MT", "country": "Malta",
                "latitude": 36.0, "longitude": 14.3,
                "bounds": {"min_lat": 35.7, "max_lat": 36.3, "min_lon": 14.0, "max_lon": 14.6},
                "tagline": "Mediterranean's dive capital with wrecks and caves",
                "best_season": "April–October",
                "defaults": {
                    "averageDepth": 15.0, "maxDepth": 40.0, "averageTemp": 22.0,
                    "averageVisibility": 20.0, "difficulty": "Intermediate",
                    "curation_score": 9.0, "popularity_score": 8.8, "access_level": "shore",
                },
                "_sites": [
                    ("Blue Hole Gozo", "Cave", "Intermediate", ["arch", "chimney", "cavern", "azure window"], ["caves-cenotes"]),
                    ("HMS Maori Wreck", "Wreck", "Intermediate", ["WWII wreck", "shallow", "reef fish"], ["wreck-capitals"]),
                    ("Um El Faroud", "Wreck", "Intermediate", ["large tanker wreck", "reef fish", "deep"], ["wreck-capitals"]),
                    ("MV Karwela", "Wreck", "Intermediate", ["intentionally sunk", "reef fish"], ["wreck-capitals"]),
                    ("MV Cominoland", "Wreck", "Beginner", ["shallow wreck", "reef fish"], ["wreck-capitals", "beginner-friendly"]),
                    ("Inland Sea Gozo", "Cave", "Beginner", ["tunnel", "cavern", "exit to open sea"], ["caves-cenotes", "beginner-friendly"]),
                    ("Blue Lagoon Comino", "Reef", "Beginner", ["clear water", "reef fish", "snorkel"], ["beginner-friendly"]),
                    ("Il-Qawra Point", "Reef", "Intermediate", ["reef", "fish diversity"], []),
                    ("Delimara Point", "Reef", "Intermediate", ["reef", "amberjack", "fish"], []),
                    ("Cirkewwa", "Reef", "Beginner", ["archways", "reef fish", "shore"], ["beginner-friendly"]),
                ],
            },
            {
                "id": "croatia-adriatic",
                "name": "Croatia & Adriatic",
                "country_id": "HR", "country": "Croatia",
                "latitude": 43.5, "longitude": 16.5,
                "bounds": {"min_lat": 42.0, "max_lat": 45.5, "min_lon": 13.5, "max_lon": 19.0},
                "tagline": "Caves, wrecks, and adriatic blue",
                "best_season": "May–October",
                "defaults": {
                    "averageDepth": 15.0, "maxDepth": 35.0, "averageTemp": 20.0,
                    "averageVisibility": 20.0, "difficulty": "Beginner",
                    "curation_score": 8.5, "popularity_score": 8.0, "access_level": "boat",
                },
                "_sites": [
                    ("Baron Gautsch Wreck", "Wreck", "Advanced", ["deep wreck", "history", "reef fish"], ["wreck-capitals", "advanced-challenges"]),
                    ("Blue Cave Bisevo", "Cave", "Beginner", ["blue light phenomenon", "scenic", "snorkel"], ["caves-cenotes", "beginner-friendly"]),
                    ("Vis Island Wrecks", "Wreck", "Advanced", ["WWII wrecks", "deep", "history"], ["wreck-capitals", "advanced-challenges"]),
                    ("Green Cave Vis", "Cave", "Intermediate", ["cave", "bioluminescence", "scenic"], ["caves-cenotes"]),
                    ("Jabuka Pinnacle", "Reef", "Advanced", ["remote pinnacle", "current", "pelagic"], ["advanced-challenges"]),
                    ("Palagruza", "Reef", "Advanced", ["remote", "groupers", "reef fish"], ["advanced-challenges"]),
                    ("Red Coral Cave", "Cave", "Intermediate", ["red coral", "cave", "fish"], ["caves-cenotes"]),
                    ("Kornati Islands", "Reef", "Intermediate", ["walls", "fish diversity", "sponges"], []),
                ],
            },
            {
                "id": "canary-islands",
                "name": "Canary Islands",
                "country_id": "ES", "country": "Spain",
                "latitude": 28.3, "longitude": -15.5,
                "bounds": {"min_lat": 27.5, "max_lat": 29.5, "min_lon": -18.2, "max_lon": -13.3},
                "tagline": "Atlantic diving year-round, angel sharks, and rays",
                "best_season": "Year-round",
                "defaults": {
                    "averageDepth": 16.0, "maxDepth": 35.0, "averageTemp": 21.0,
                    "averageVisibility": 20.0, "difficulty": "Beginner",
                    "curation_score": 8.5, "popularity_score": 8.5, "access_level": "boat",
                },
                "_sites": [
                    ("El Cabron Marine Reserve", "Reef", "Intermediate", ["angel sharks", "endemic species", "marine reserve"], ["big-animals"]),
                    ("Arguineguin Cathedral", "Cave", "Intermediate", ["cathedral cavern", "reef fish", "light"], ["caves-cenotes"]),
                    ("Lanzarote Museum", "Reef", "Beginner", ["underwater museum", "sculptures", "artificial reef"], ["beginner-friendly"]),
                    ("Los Jameos Caves", "Cave", "Intermediate", ["volcanic caves", "unique fauna"], ["caves-cenotes"]),
                    ("Tenerife Wrecks", "Wreck", "Intermediate", ["multiple wrecks", "reef fish"], ["wreck-capitals"]),
                    ("La Palma", "Reef", "Intermediate", ["black sand", "lava formations", "macro"], ["macro-muck"]),
                    ("La Gomera", "Reef", "Intermediate", ["volcanic reef", "fish diversity"], []),
                    ("Puerto del Carmen", "Shore", "Beginner", ["shore diving", "reef fish", "eels"], ["beginner-friendly"]),
                ],
            },
            {
                "id": "azores-madeira",
                "name": "Azores & Madeira",
                "country_id": "PT", "country": "Portugal",
                "latitude": 38.7, "longitude": -27.2,
                "bounds": {"min_lat": 36.0, "max_lat": 40.0, "min_lon": -32.0, "max_lon": -25.0},
                "tagline": "Pelagic encounters in the mid-Atlantic",
                "best_season": "June–October",
                "defaults": {
                    "averageDepth": 18.0, "maxDepth": 40.0, "averageTemp": 21.0,
                    "averageVisibility": 22.0, "difficulty": "Advanced",
                    "curation_score": 9.2, "popularity_score": 8.0, "access_level": "boat",
                },
                "_sites": [
                    ("Dollabarat Shoal", "Reef", "Advanced", ["blue sharks", "mako sharks", "pelagic"], ["big-animals", "advanced-challenges"]),
                    ("Formigas Shoal", "Reef", "Advanced", ["hammerheads", "mobula rays", "pelagic"], ["big-animals", "advanced-challenges"]),
                    ("Princess Alice Bank", "Reef", "Advanced", ["whale sharks", "hammerheads", "remote"], ["big-animals", "advanced-challenges"]),
                    ("Santa Maria Caves", "Cave", "Intermediate", ["volcanic caves", "reef fish"], ["caves-cenotes"]),
                    ("Stingray City Azores", "Reef", "Beginner", ["stingrays", "reef fish", "calm"], ["big-animals", "beginner-friendly"]),
                    ("Dom Joao de Castro Bank", "Reef", "Advanced", ["volcanic seamount", "pelagic", "unique fauna"], ["advanced-challenges"]),
                ],
            },
        ],
    },

    # =========================================================================
    # 13. CENTRAL AMERICA & MEXICO PACIFIC
    # =========================================================================
    {
        "id": "central-america-mexico-pacific",
        "name": "Central America & Mexico Pacific",
        "tagline": "Whale sharks, hammerheads, and pristine Pacific reefs",
        "description": "",
        "sort_order": 13,
        "regions": [
            {
                "id": "galapagos",
                "name": "Galápagos Islands",
                "country_id": "EC", "country": "Ecuador",
                "latitude": -0.8, "longitude": -90.9,
                "bounds": {"min_lat": -1.6, "max_lat": 0.7, "min_lon": -92.0, "max_lon": -89.0},
                "tagline": "Darwin's paradise — hammerheads, whale sharks, and marine iguanas",
                "best_season": "December–May",
                "defaults": {
                    "averageDepth": 18.0, "maxDepth": 35.0, "averageTemp": 22.0,
                    "averageVisibility": 15.0, "difficulty": "Advanced",
                    "curation_score": 9.7, "popularity_score": 9.3, "access_level": "liveaboard",
                },
                "_sites": [
                    ("Wolf Island", "Reef", "Advanced", ["whale sharks", "hammerheads", "schooling fish", "silky sharks"], ["big-animals", "liveaboard", "advanced-challenges"]),
                    ("Darwin Island", "Reef", "Advanced", ["whale sharks", "hammerheads", "large pelagic"], ["big-animals", "liveaboard", "advanced-challenges"]),
                    ("Gordon Rocks", "Drift", "Advanced", ["hammerheads", "current", "schooling fish"], ["big-animals", "advanced-challenges"]),
                    ("Kicker Rock", "Drift", "Advanced", ["hammerheads", "rays", "current", "pelagic"], ["big-animals", "advanced-challenges"]),
                    ("North Seymour", "Reef", "Intermediate", ["reef fish", "sea lions", "marine iguanas"], ["big-animals"]),
                    ("Cousins Rock", "Reef", "Advanced", ["seahorses", "hammerheads", "schooling fish"], ["big-animals", "macro-muck"]),
                    ("Devil's Crown", "Reef", "Intermediate", ["reef", "turtles", "fish diversity"], []),
                    ("Bartolomé", "Reef", "Intermediate", ["penguins", "fish", "unique landscape"], ["big-animals"]),
                    ("Mosquera", "Reef", "Beginner", ["sea lions", "reef fish", "turtles"], ["big-animals", "beginner-friendly"]),
                ],
            },
            {
                "id": "cocos-island",
                "name": "Cocos Island, Costa Rica",
                "country_id": "CR", "country": "Costa Rica",
                "latitude": 5.5, "longitude": -87.1,
                "bounds": {"min_lat": 5.3, "max_lat": 5.7, "min_lon": -87.4, "max_lon": -86.9},
                "tagline": "Hammerhead aggregations and whale shark highway",
                "best_season": "May–December",
                "defaults": {
                    "averageDepth": 20.0, "maxDepth": 40.0, "averageTemp": 27.0,
                    "averageVisibility": 15.0, "difficulty": "Advanced",
                    "curation_score": 9.8, "popularity_score": 8.8, "access_level": "liveaboard",
                },
                "_sites": [
                    ("Dirty Rock", "Reef", "Advanced", ["hammerheads", "whale sharks", "schooling fish"], ["big-animals", "liveaboard", "advanced-challenges"]),
                    ("Manuelita", "Reef", "Advanced", ["white tip reef sharks", "hammerheads", "current"], ["big-animals", "liveaboard", "advanced-challenges"]),
                    ("Alcyone Seamount", "Reef", "Advanced", ["hammerheads", "whale sharks", "eagle rays"], ["big-animals", "liveaboard", "advanced-challenges"]),
                    ("Bajo Alcyone", "Reef", "Advanced", ["whale sharks", "hammerheads", "strong current"], ["big-animals", "liveaboard", "advanced-challenges"]),
                    ("Dos Amigos Grande", "Reef", "Advanced", ["bull sharks", "hammerheads", "current"], ["big-animals", "liveaboard"]),
                ],
            },
            {
                "id": "sea-of-cortez",
                "name": "Sea of Cortez & Baja California",
                "country_id": "MX", "country": "Mexico",
                "latitude": 26.0, "longitude": -110.5,
                "bounds": {"min_lat": 22.0, "max_lat": 31.0, "min_lon": -115.0, "max_lon": -108.0},
                "tagline": "Whale sharks, sea lions, and the world's aquarium",
                "best_season": "October–June",
                "defaults": {
                    "averageDepth": 16.0, "maxDepth": 35.0, "averageTemp": 24.0,
                    "averageVisibility": 18.0, "difficulty": "Intermediate",
                    "curation_score": 9.0, "popularity_score": 8.5, "access_level": "boat",
                },
                "_sites": [
                    ("El Bajo Seamount", "Reef", "Advanced", ["hammerheads", "mobula rays", "current"], ["big-animals", "advanced-challenges"]),
                    ("Los Islotes", "Reef", "Beginner", ["sea lions", "playful", "reef fish"], ["big-animals", "beginner-friendly"]),
                    ("La Reina", "Reef", "Intermediate", ["schooling fish", "grouper", "reef"], []),
                    ("Cabo Pulmo", "Reef", "Intermediate", ["living reef", "bull sharks", "fish density"], ["big-animals"]),
                    ("Gordo Banks", "Reef", "Advanced", ["whale sharks", "hammerheads", "current"], ["big-animals", "advanced-challenges"]),
                    ("Santa Cruz Island", "Reef", "Intermediate", ["sea lions", "fish diversity"], ["big-animals"]),
                    ("San Diego Canyon", "Reef", "Advanced", ["whale sharks", "deep canyon", "pelagic"], ["big-animals", "advanced-challenges"]),
                    ("Shallow Seamount", "Reef", "Advanced", ["hammerheads", "eagle rays", "schools"], ["big-animals", "advanced-challenges"]),
                ],
            },
            {
                "id": "socorro-revillagigedo",
                "name": "Socorro (Revillagigedo Islands)",
                "country_id": "MX", "country": "Mexico",
                "latitude": 18.8, "longitude": -110.9,
                "bounds": {"min_lat": 17.0, "max_lat": 21.0, "min_lon": -112.0, "max_lon": -109.0},
                "tagline": "Giant mantas and Pacific pelagic powerhouse",
                "best_season": "November–May",
                "defaults": {
                    "averageDepth": 20.0, "maxDepth": 40.0, "averageTemp": 26.0,
                    "averageVisibility": 25.0, "difficulty": "Advanced",
                    "curation_score": 9.7, "popularity_score": 9.0, "access_level": "liveaboard",
                },
                "_sites": [
                    ("The Boiler Socorro", "Reef", "Advanced", ["giant mantas", "whale sharks", "hammerheads", "dolphins"], ["big-animals", "liveaboard", "advanced-challenges"]),
                    ("Roca Partida", "Reef", "Advanced", ["hammerheads", "silky sharks", "whale sharks"], ["big-animals", "liveaboard", "advanced-challenges"]),
                    ("Canyon Socorro", "Reef", "Advanced", ["giant mantas", "hammerheads", "schooling fish"], ["big-animals", "liveaboard"]),
                    ("Cabo Pearce", "Reef", "Advanced", ["giant mantas", "dolphins", "sharks"], ["big-animals", "liveaboard"]),
                ],
            },
            {
                "id": "panama-colombia-pacific",
                "name": "Panama Pacific & Colombia",
                "country_id": "PA", "country": "Panama",
                "latitude": 7.5, "longitude": -81.7,
                "bounds": {"min_lat": 1.0, "max_lat": 9.5, "min_lon": -84.0, "max_lon": -75.0},
                "tagline": "Hammerheads, whale sharks, and pristine Pacific reefs",
                "best_season": "July–October",
                "defaults": {
                    "averageDepth": 18.0, "maxDepth": 40.0, "averageTemp": 27.0,
                    "averageVisibility": 15.0, "difficulty": "Advanced",
                    "curation_score": 9.1, "popularity_score": 7.5, "access_level": "liveaboard",
                },
                "_sites": [
                    ("Coiba Island Panama", "Reef", "Advanced", ["UNESCO", "whale sharks", "hammerheads", "pristine"], ["big-animals", "liveaboard", "advanced-challenges"]),
                    ("Malpelo Island", "Reef", "Advanced", ["hammerheads", "whale sharks", "silky sharks", "remote"], ["big-animals", "liveaboard", "advanced-challenges"]),
                    ("Hannibal Bank", "Reef", "Advanced", ["whale sharks", "mobula rays", "hammerheads"], ["big-animals", "liveaboard"]),
                    ("Isla de la Plata", "Reef", "Intermediate", ["blue-footed boobies", "whale sharks", "mantas"], ["big-animals"]),
                ],
            },
        ],
    },

    # =========================================================================
    # 14. SOUTH AMERICA
    # =========================================================================
    {
        "id": "south-america",
        "name": "South America",
        "tagline": "Fernando de Noronha, cold kelp forests, and Amazon coral",
        "description": "",
        "sort_order": 14,
        "regions": [
            {
                "id": "fernando-de-noronha",
                "name": "Fernando de Noronha, Brazil",
                "country_id": "BR", "country": "Brazil",
                "latitude": -3.85, "longitude": -32.4,
                "bounds": {"min_lat": -4.0, "max_lat": -3.7, "min_lon": -32.6, "max_lon": -32.2},
                "tagline": "Brazil's hidden paradise of spinner dolphins",
                "best_season": "September–March",
                "defaults": {
                    "averageDepth": 16.0, "maxDepth": 35.0, "averageTemp": 28.0,
                    "averageVisibility": 25.0, "difficulty": "Intermediate",
                    "curation_score": 9.3, "popularity_score": 8.5, "access_level": "boat",
                },
                "_sites": [
                    ("Enseada dos Tubarões", "Reef", "Intermediate", ["reef sharks", "fish diversity", "reef"], ["big-animals"]),
                    ("Cagarras da Conceição", "Reef", "Intermediate", ["clear water", "reef fish", "turtles"], []),
                    ("Corveta Ipiranga Wreck", "Wreck", "Advanced", ["corvette wreck", "reef fish", "history"], ["wreck-capitals", "advanced-challenges"]),
                    ("Pedra do Atalaia", "Reef", "Advanced", ["sharks", "pelagic", "current"], ["big-animals", "advanced-challenges"]),
                    ("Buraco das Cabras", "Cave", "Intermediate", ["cavern", "fish", "coral"], ["caves-cenotes"]),
                    ("Ponta da Sapata", "Reef", "Advanced", ["current", "pelagic", "reef sharks"], ["big-animals", "advanced-challenges"]),
                ],
            },
            {
                "id": "patagonia-chile",
                "name": "Patagonia & Chilean Fjords",
                "country_id": "CL", "country": "Chile",
                "latitude": -45.0, "longitude": -73.0,
                "bounds": {"min_lat": -55.0, "max_lat": -40.0, "min_lon": -76.0, "max_lon": -67.0},
                "tagline": "Kelp forests, sea lions, and extreme cold-water adventure",
                "best_season": "January–March",
                "defaults": {
                    "averageDepth": 14.0, "maxDepth": 25.0, "averageTemp": 10.0,
                    "averageVisibility": 8.0, "difficulty": "Advanced",
                    "curation_score": 8.5, "popularity_score": 6.0, "access_level": "boat",
                },
                "_sites": [
                    ("Magellanic Strait", "Reef", "Advanced", ["kelp forest", "sea lions", "cold water"], ["cold-water", "advanced-challenges"]),
                    ("Easter Island", "Reef", "Intermediate", ["clear water", "endemic fish", "unique"], []),
                    ("Robinson Crusoe Island", "Reef", "Intermediate", ["endemic fish", "remote", "unique"], []),
                    ("Chiloe Island", "Shore", "Advanced", ["kelp", "cold water", "sea lions"], ["cold-water", "advanced-challenges"]),
                ],
            },
        ],
    },

    # =========================================================================
    # 15. NORTH ATLANTIC & COLD WATER
    # =========================================================================
    {
        "id": "cold-water-north-atlantic",
        "name": "North Atlantic & Cold Water",
        "tagline": "Icebergs, kelp forests, and incredible sea life density",
        "description": "",
        "sort_order": 15,
        "regions": [
            {
                "id": "norway-lofoten",
                "name": "Norway & Lofoten",
                "country_id": "NO", "country": "Norway",
                "latitude": 68.0, "longitude": 14.5,
                "bounds": {"min_lat": 62.0, "max_lat": 71.0, "min_lon": 5.0, "max_lon": 30.0},
                "tagline": "Orcas, king crabs, and Arctic diving",
                "best_season": "November–January (orcas), June–August (visibility)",
                "defaults": {
                    "averageDepth": 15.0, "maxDepth": 30.0, "averageTemp": 8.0,
                    "averageVisibility": 15.0, "difficulty": "Advanced",
                    "curation_score": 9.0, "popularity_score": 7.0, "access_level": "boat",
                },
                "_sites": [
                    ("Tysfjord Orcas", "Reef", "Advanced", ["orca", "herring", "cold water", "Arctic"], ["big-animals", "cold-water", "advanced-challenges"]),
                    ("Oksfjord", "Reef", "Advanced", ["king crabs", "cold water", "fish"], ["cold-water", "advanced-challenges"]),
                    ("Runde Island", "Reef", "Intermediate", ["puffins", "cold water", "fish"], ["cold-water"]),
                    ("Sognefjord Wrecks", "Wreck", "Intermediate", ["fjord wrecks", "cold water", "history"], ["wreck-capitals", "cold-water"]),
                    ("Saltstraumen", "Drift", "Advanced", ["strongest maelstrom", "current", "fish density"], ["cold-water", "advanced-challenges"]),
                    ("Svalbard", "Reef", "Advanced", ["Arctic", "polar bears", "beluga whales", "extreme cold"], ["cold-water", "liveaboard", "advanced-challenges"]),
                ],
            },
            {
                "id": "scotland-uk",
                "name": "Scotland & UK",
                "country_id": "GB", "country": "United Kingdom",
                "latitude": 57.5, "longitude": -4.5,
                "bounds": {"min_lat": 50.0, "max_lat": 61.0, "min_lon": -8.0, "max_lon": 2.0},
                "tagline": "Basking sharks, seals, and outstanding wrecks",
                "best_season": "April–September",
                "defaults": {
                    "averageDepth": 15.0, "maxDepth": 35.0, "averageTemp": 12.0,
                    "averageVisibility": 8.0, "difficulty": "Advanced",
                    "curation_score": 8.8, "popularity_score": 7.2, "access_level": "boat",
                },
                "_sites": [
                    ("Scapa Flow Wrecks", "Wreck", "Intermediate", ["WWI German fleet", "multiple wrecks", "history"], ["wreck-capitals"]),
                    ("Farne Islands", "Shore", "Intermediate", ["grey seals", "playful", "cold water"], ["big-animals", "cold-water"]),
                    ("Lundy Island", "Reef", "Intermediate", ["grey seals", "marine reserve", "cold water"], ["big-animals", "cold-water"]),
                    ("SS Thesis Wreck", "Wreck", "Intermediate", ["wreck", "reef fish", "cold water"], ["wreck-capitals", "cold-water"]),
                    ("Mull Wrecks", "Wreck", "Intermediate", ["wrecks", "cold water", "history"], ["wreck-capitals", "cold-water"]),
                    ("St Abbs Marine Reserve", "Shore", "Intermediate", ["marine reserve", "kelp", "fish"], ["cold-water"]),
                    ("Sound of Mull", "Wreck", "Intermediate", ["wreck diving", "cold water", "fish"], ["wreck-capitals", "cold-water"]),
                    ("Oban", "Shore", "Intermediate", ["cold water", "nudibranchs", "macro"], ["macro-muck", "cold-water"]),
                ],
            },
            {
                "id": "iceland-greenland",
                "name": "Iceland & Greenland",
                "country_id": "IS", "country": "Iceland",
                "latitude": 64.5, "longitude": -18.0,
                "bounds": {"min_lat": 63.0, "max_lat": 67.0, "min_lon": -24.5, "max_lon": -13.0},
                "tagline": "Crystal clear geothermal diving and icebergs",
                "best_season": "May–September",
                "defaults": {
                    "averageDepth": 10.0, "maxDepth": 20.0, "averageTemp": 4.0,
                    "averageVisibility": 30.0, "difficulty": "Intermediate",
                    "curation_score": 9.2, "popularity_score": 7.5, "access_level": "boat",
                },
                "_sites": [
                    ("Silfra Fissure", "Cave", "Intermediate", ["tectonic plates", "crystal clear", "freshwater", "unique"], ["caves-cenotes", "cold-water"]),
                    ("Davíðsgjá", "Cave", "Intermediate", ["fissure", "freshwater", "clear"], ["caves-cenotes", "cold-water"]),
                    ("Strýtan Hydrothermal Chimney", "Reef", "Intermediate", ["geothermal", "unique", "macro"], ["cold-water"]),
                    ("Kleifarvatn Lake", "Reef", "Advanced", ["geothermal lake", "unique", "extreme conditions"], ["cold-water", "advanced-challenges"]),
                ],
            },
            {
                "id": "canada-pacific",
                "name": "British Columbia & Pacific Canada",
                "country_id": "CA", "country": "Canada",
                "latitude": 50.0, "longitude": -125.0,
                "bounds": {"min_lat": 48.0, "max_lat": 54.0, "min_lon": -130.0, "max_lon": -122.0},
                "tagline": "Giant Pacific octopus, wolf eels, and kelp forests",
                "best_season": "November–April (plankton blooms clear)",
                "defaults": {
                    "averageDepth": 15.0, "maxDepth": 30.0, "averageTemp": 9.0,
                    "averageVisibility": 10.0, "difficulty": "Intermediate",
                    "curation_score": 9.0, "popularity_score": 7.5, "access_level": "shore",
                },
                "_sites": [
                    ("Browning Wall", "Wall", "Advanced", ["nudibranch density", "rockfish", "cold water"], ["macro-muck", "cold-water", "advanced-challenges"]),
                    ("God's Pocket", "Reef", "Intermediate", ["marine reserve", "wolf eels", "octopus"], ["cold-water"]),
                    ("Nakwakto Rapids", "Drift", "Advanced", ["fastest tidal rapid", "extreme current", "fish"], ["cold-water", "advanced-challenges"]),
                    ("Race Rocks", "Reef", "Advanced", ["marine reserve", "sea lions", "seals", "orcas"], ["big-animals", "cold-water", "advanced-challenges"]),
                    ("Octopus Gardens", "Shore", "Intermediate", ["giant pacific octopus", "kelp", "macro"], ["macro-muck", "cold-water"]),
                    ("Tuwanek", "Shore", "Beginner", ["shore", "fish", "macro"], ["cold-water", "beginner-friendly"]),
                    ("Dodd Narrows", "Drift", "Advanced", ["current", "fish density", "cold water"], ["cold-water", "advanced-challenges"]),
                ],
            },
        ],
    },

    # =========================================================================
    # 16. JAPAN & EAST ASIA
    # =========================================================================
    {
        "id": "japan-east-asia",
        "name": "Japan & East Asia",
        "tagline": "Hammerheads, nudibranchs, and WWII wrecks",
        "description": "",
        "sort_order": 16,
        "regions": [
            {
                "id": "okinawa-japan",
                "name": "Okinawa, Japan",
                "country_id": "JP", "country": "Japan",
                "latitude": 26.5, "longitude": 128.0,
                "bounds": {"min_lat": 24.0, "max_lat": 28.5, "min_lon": 122.0, "max_lon": 131.0},
                "tagline": "Whale sharks, mantas, and WWII wrecks",
                "best_season": "May–October",
                "defaults": {
                    "averageDepth": 16.0, "maxDepth": 35.0, "averageTemp": 26.0,
                    "averageVisibility": 20.0, "difficulty": "Intermediate",
                    "curation_score": 9.0, "popularity_score": 8.5, "access_level": "boat",
                },
                "_sites": [
                    ("USS Emmons Wreck", "Wreck", "Advanced", ["WWII destroyer", "deep wreck", "history"], ["wreck-capitals", "advanced-challenges"]),
                    ("Miyako Blue Cave", "Cave", "Beginner", ["blue light", "cave", "reef fish"], ["caves-cenotes", "beginner-friendly"]),
                    ("Yonaguni Monument", "Reef", "Intermediate", ["mysterious structure", "hammerheads", "unique"], ["big-animals"]),
                    ("Manta Scramble Ishigaki", "Reef", "Intermediate", ["manta rays", "cleaning station"], ["big-animals"]),
                    ("Blue Cave Okinawa", "Cave", "Beginner", ["famous cave", "blue light", "reef fish"], ["caves-cenotes", "beginner-friendly"]),
                    ("Sunayama Beach", "Shore", "Beginner", ["shore", "reef fish", "turtles"], ["beginner-friendly"]),
                    ("Kerama Islands", "Reef", "Intermediate", ["turtles", "coral", "fish diversity"], []),
                    ("Maeda Point", "Reef", "Intermediate", ["arch", "swimthrough", "reef fish"], []),
                    ("Kuroshima", "Reef", "Intermediate", ["remote", "pristine coral", "fish"], []),
                ],
            },
            {
                "id": "izu-peninsula-japan",
                "name": "Izu Peninsula & Sagami Bay",
                "country_id": "JP", "country": "Japan",
                "latitude": 34.7, "longitude": 138.9,
                "bounds": {"min_lat": 34.5, "max_lat": 35.3, "min_lon": 138.7, "max_lon": 140.0},
                "tagline": "World-class macro and incredible nudibranch diversity",
                "best_season": "Year-round; winter for nudibranchs",
                "defaults": {
                    "averageDepth": 16.0, "maxDepth": 35.0, "averageTemp": 18.0,
                    "averageVisibility": 12.0, "difficulty": "Intermediate",
                    "curation_score": 8.8, "popularity_score": 8.5, "access_level": "shore",
                },
                "_sites": [
                    ("Osezaki", "Shore", "Intermediate", ["macro", "nudibranchs", "seahorse"], ["macro-muck"]),
                    ("Futo", "Shore", "Intermediate", ["macro", "nudibranchs", "octopus"], ["macro-muck"]),
                    ("Yawatano", "Shore", "Beginner", ["macro", "reef fish", "shore"], ["macro-muck", "beginner-friendly"]),
                    ("Kumomi", "Shore", "Intermediate", ["seahorse", "macro", "nudibranchs"], ["macro-muck"]),
                    ("Ogasawara Islands", "Reef", "Intermediate", ["dolphins", "humpback whales", "reef fish", "remote"], ["big-animals"]),
                ],
            },
            {
                "id": "taiwan",
                "name": "Taiwan & Green Island",
                "country_id": "TW", "country": "Taiwan",
                "latitude": 22.65, "longitude": 121.5,
                "bounds": {"min_lat": 21.5, "max_lat": 25.5, "min_lon": 120.0, "max_lon": 122.5},
                "tagline": "Current-swept pinnacles and underwater hot springs",
                "best_season": "April–October",
                "defaults": {
                    "averageDepth": 16.0, "maxDepth": 35.0, "averageTemp": 26.0,
                    "averageVisibility": 15.0, "difficulty": "Intermediate",
                    "curation_score": 8.5, "popularity_score": 7.8, "access_level": "boat",
                },
                "_sites": [
                    ("Green Island Hot Springs Underwater", "Reef", "Intermediate", ["underwater hot springs", "unique", "reef fish"], []),
                    ("Little Liuqiu", "Shore", "Beginner", ["turtles", "shore diving", "reef fish"], ["beginner-friendly"]),
                    ("Orchid Island Whaleshark", "Reef", "Intermediate", ["whale sharks", "reef fish", "Tao culture"], ["big-animals"]),
                    ("Kenting National Park", "Reef", "Beginner", ["coral", "reef fish", "protected"], ["beginner-friendly"]),
                    ("Penghu Islands", "Reef", "Intermediate", ["basalt formations", "reef fish", "macro"], []),
                ],
            },
            {
                "id": "korea-china-seas",
                "name": "South Korea & Yellow Sea",
                "country_id": "KR", "country": "South Korea",
                "latitude": 34.5, "longitude": 127.0,
                "bounds": {"min_lat": 33.0, "max_lat": 38.0, "min_lon": 124.0, "max_lon": 130.0},
                "tagline": "Haenyeo heritage and cold-water wrecks",
                "best_season": "July–September",
                "defaults": {
                    "averageDepth": 12.0, "maxDepth": 25.0, "averageTemp": 19.0,
                    "averageVisibility": 8.0, "difficulty": "Intermediate",
                    "curation_score": 7.5, "popularity_score": 6.5, "access_level": "boat",
                },
                "_sites": [
                    ("Jeju Island", "Shore", "Intermediate", ["basalt columns", "unique fauna", "cold water"], ["cold-water"]),
                    ("Seogwipo", "Reef", "Intermediate", ["reef fish", "wrecks", "macro"], []),
                    ("Oedo Island", "Reef", "Beginner", ["garden island", "reef fish"], ["beginner-friendly"]),
                    ("Dokdo", "Reef", "Advanced", ["remote", "pelagic", "sea lions"], ["big-animals", "advanced-challenges"]),
                ],
            },
        ],
    },

    # =========================================================================
    # 17. SOUTH AFRICA & SOUTH ATLANTIC
    # =========================================================================
    {
        "id": "south-africa-south-atlantic",
        "name": "South Africa & South Atlantic",
        "tagline": "Sardine run, great whites, and cape fur seals",
        "description": "",
        "sort_order": 17,
        "regions": [
            {
                "id": "south-africa-eastern-cape",
                "name": "KwaZulu-Natal & Eastern Cape",
                "country_id": "ZA", "country": "South Africa",
                "latitude": -29.8, "longitude": 31.0,
                "bounds": {"min_lat": -35.0, "max_lat": -27.0, "min_lon": 27.0, "max_lon": 33.0},
                "tagline": "Sardine run, tiger sharks, and epic pelagics",
                "best_season": "June–July (sardine run); November–April (clear water)",
                "defaults": {
                    "averageDepth": 16.0, "maxDepth": 35.0, "averageTemp": 22.0,
                    "averageVisibility": 10.0, "difficulty": "Advanced",
                    "curation_score": 9.2, "popularity_score": 8.5, "access_level": "boat",
                },
                "_sites": [
                    ("Aliwal Shoal", "Reef", "Advanced", ["ragged tooth sharks", "tiger sharks", "current"], ["big-animals", "advanced-challenges"]),
                    ("Protea Banks", "Reef", "Advanced", ["hammerheads", "bull sharks", "tiger sharks"], ["big-animals", "advanced-challenges"]),
                    ("Sardine Run", "Reef", "Intermediate", ["sardine baitball", "dolphins", "sharks", "gannets"], ["big-animals"]),
                    ("Lesleen M Wreck", "Wreck", "Intermediate", ["wreck", "reef fish", "nudibranch"], ["wreck-capitals"]),
                    ("Produce Wreck", "Wreck", "Intermediate", ["wreck", "reef fish"], ["wreck-capitals"]),
                    ("Sodwana Bay", "Reef", "Intermediate", ["reef fish", "soft coral", "turtles"], []),
                    ("Two-Mile Reef Sodwana", "Reef", "Intermediate", ["pristine reef", "fish diversity"], []),
                    ("Seven-Mile Reef", "Reef", "Advanced", ["pristine deep reef", "ragged tooth sharks"], ["big-animals", "advanced-challenges"]),
                ],
            },
            {
                "id": "south-africa-western-cape",
                "name": "Western Cape & False Bay",
                "country_id": "ZA", "country": "South Africa",
                "latitude": -34.1, "longitude": 18.5,
                "bounds": {"min_lat": -35.0, "max_lat": -33.0, "min_lon": 17.5, "max_lon": 19.5},
                "tagline": "Great white sharks, cape fur seals, and cold Atlantic reefs",
                "best_season": "June–October (great whites); December–March (seals)",
                "defaults": {
                    "averageDepth": 12.0, "maxDepth": 25.0, "averageTemp": 14.0,
                    "averageVisibility": 8.0, "difficulty": "Intermediate",
                    "curation_score": 9.0, "popularity_score": 8.8, "access_level": "boat",
                },
                "_sites": [
                    ("Gansbaai Shark Cage Diving", "Reef", "Beginner", ["great white sharks", "cage diving", "surface"], ["big-animals", "beginner-friendly"]),
                    ("Seal Island False Bay", "Reef", "Advanced", ["great white breaching", "seals", "cold water"], ["big-animals", "cold-water", "advanced-challenges"]),
                    ("Boulders Beach Seals", "Shore", "Beginner", ["cape fur seals", "shore", "snorkel"], ["big-animals", "beginner-friendly"]),
                    ("Atlantic Seaboard Reefs", "Reef", "Intermediate", ["cold water", "reef fish", "macro"], ["cold-water"]),
                    ("SAS Pietermaritzburg Wreck", "Wreck", "Intermediate", ["navy wreck", "artificial reef", "reef fish"], ["wreck-capitals"]),
                    ("Gordon's Bay Wrecks", "Wreck", "Intermediate", ["multiple wrecks", "reef fish", "cold water"], ["wreck-capitals", "cold-water"]),
                    ("Smitswinkel Bay Wrecks", "Wreck", "Intermediate", ["4 wrecks", "reef fish", "kelp"], ["wreck-capitals", "cold-water"]),
                ],
            },
            {
                "id": "st-helena-ascension",
                "name": "St. Helena & Ascension Island",
                "country_id": "SH", "country": "Saint Helena",
                "latitude": -15.9, "longitude": -5.7,
                "bounds": {"min_lat": -16.1, "max_lat": -15.7, "min_lon": -5.9, "max_lon": -5.5},
                "tagline": "Napoleon's exile island — whale sharks and pristine Atlantic reefs",
                "best_season": "November–April",
                "defaults": {
                    "averageDepth": 18.0, "maxDepth": 35.0, "averageTemp": 22.0,
                    "averageVisibility": 25.0, "difficulty": "Intermediate",
                    "curation_score": 9.0, "popularity_score": 6.0, "access_level": "boat",
                },
                "_sites": [
                    ("The Speery Island", "Reef", "Intermediate", ["endemic fish", "pristine reef", "remote"], []),
                    ("Napoleon's Bathtub", "Shore", "Beginner", ["clear water", "reef fish", "history"], ["beginner-friendly"]),
                    ("Whale Shark Aggregation", "Reef", "Intermediate", ["whale sharks", "unique aggregation", "remote"], ["big-animals"]),
                    ("Castle Rock Ascension", "Reef", "Advanced", ["endemic species", "remote", "pelagic"], ["big-animals", "liveaboard", "advanced-challenges"]),
                ],
            },
        ],
    },

]
